samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.cs

fix: Avoid SystemNavigationManager calls for WinUI

---

src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Base.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Mobile.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.xaml

- Bugfix
Modal navigation bars do not show on Android
Modal navigation bars DO show on Android

fix: Fix Modal styles for NavigationBar

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/MaterialBottomBarSampleNestedPage.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.Mobile.xaml

closes https://github.com/unoplatform/uno.toolkit.ui/issues/163
- Bugfix
Results:

fix: Use proper fab tabbaritem style

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.cs

fix: Add null check for Page.Frame

---

.mergify.yml
src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Base.xaml

fix: Properly apply Padding on NavigationBar's CommandBar

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs

- Bugfix
Toolkit uses a `TryGetColorWithOpacity` method from its `ColorHelper` [here](https://github.com/unoplatform/uno.toolkit.ui/blob/39810a2eb6d1e9ad33d672095c24f37fb7ce33c5/src/Uno.Toolkit.UI/Helpers/ColorHelper.cs#L32-L49)
There are certain cases where we do not check if `TryGetColorWithOpacity` returns `false` and would then use the `color` that was set by the method. Problem is that default(Windows.UI.Color) returns a color of `#00000000` and not `null`. The code is structured in a way that it is expecting a `null` as a fallback. This was causing issues such as the UIBarButtonItem's Foreground becoming transparent. We were also not allowing the default iOS UINavigationBar background to display since we would always be changing the …

fix(NavigationBar): Avoid improper Color fallbacks being set on native NavBar elements

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs

closes https://github.com/unoplatform/nventive-private/issues/351
- Bugfix

fix(NavBar): Remove 1px shadow line from iOS NavBar

---

src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

chore: Bump Microsoft.Windows.SDK.NET.Ref to 10.0.22000.24

---

build/workflow/pipeline.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Info.plist
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Info.plist
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Info.plist
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Info.plist

ci: Adjust iOS/macOS Samples app publication

---

build/Install-WindowsSdkISO.ps1
src/library/Uno.Toolkit.Material/Styles/Controls/v2/_Common.xaml
src/library/Uno.Toolkit.Material/xamlmerge.props

fix: Toolkit M3 styles need to reference Themes M3 styles

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DividerSamplePage.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/Divider.xaml

feat: Add M3 Divider style

---

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

closes unoplatform/Uno.Figma#525

chore: remove unused AutoLayout::CounterAxisAlignment

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.Navigation.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ChipSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Uno.Toolkit.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Wasm/Uno.Toolkit.Samples.Wasm.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Uno.Toolkit.WinUI.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Wasm/Uno.Toolkit.WinUI.Samples.Wasm.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Uno.Toolkit.WinUI.Samples.iOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj
src/Uno.Toolkit.UI/Controls/Chips/Chip.cs
src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.v1.xaml
src/library/Uno.Toolkit.Material/MaterialToolkitResourcesV2.cs
src/library/Uno.Toolkit.Material/Styles/Controls/v1/Chip.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/ChipGroup.xaml
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

feat: Material Design 3 Chips

---

README.md

Update Getting Started section and add synced contributors list for README.md

docs: Update Getting Started section and add synced contributors list for README.md

---

README.md
doc/controls-styles.md
doc/controls/CardAndCardContentControl.md
doc/controls/ChipAndChipGroup.md
doc/controls/DrawerControl.md
doc/controls/NavigationBar.md
doc/controls/TabBarAndTabBarItem.md
doc/getting-started.md
doc/toc.yml

Update documentation content and toc structure for Toolkit

docs: Update documentation content and toc structure for Toolkit

---

build/workflow/pipeline.yml

Change so the CI is not triggered if only docs files are changed

ci: Change so the CI is not triggered if only docs files are changed

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/TabBarSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/TabBarSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialBottomBarSampleNestedPage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialBottomBarSampleNestedPage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/library/Uno.Toolkit.Material/MaterialToolkitResourcesV2.cs
src/library/Uno.Toolkit.Material/Styles/Controls/v2/BottomTabBar.xaml

feat: Add Material 3 BottomTabBar

---

doc/material-migration.md

docs: fix doc errors

---

doc/controls-styles.md
doc/helpers/ancestor-itemscontrol-binding.md
doc/toc.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerControlSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerControlSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/TabBarBehaviorSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/BindingExtensionsSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/BindingExtensionsSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.Properties.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Entities/Design.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Entities/SamplePageAttribute.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Entities/SourceSdk.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Styles/SamplePageLayout.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/Uno.Toolkit.UI/Markup/AncestorBindingExtension.cs
src/Uno.Toolkit.UI/Markup/ItemsControlBindingExtension.cs

- Feature
Added AncestorBinding + ItemsControlsBinding
ninja fix: design-agnotic control dont have a proper page header && drawer-control sample broken with the m2/3 update (due to SamplePageLayout)

feat: ancestor & items-control bindings

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/TabBarSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Uno.Toolkit.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Wasm/Uno.Toolkit.Samples.Wasm.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Uno.Toolkit.WinUI.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Wasm/Uno.Toolkit.WinUI.Samples.Wasm.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Uno.Toolkit.WinUI.Samples.iOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.v2.xaml
src/library/Uno.Toolkit.Material/Generated/mergedpages.winui.v2.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/BottomTabBar.xaml
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

https://github.com/unoplatform/Uno.Themes/pull/802 will need to be merged and updated into Toolkit for this to build on WinUI

fix: Update BottomTabBar pointer states and colors

---

doc/controls/CardAndCardContentControl.md
doc/controls/ChipAndChipGroup.md
doc/controls/DrawerControl.md
doc/controls/NavigationBar.md
doc/controls/SegmentedControls.md
doc/controls/TabBarAndTabBarItem.md
doc/getting-started.md

Improve the documentation so it's easier to not miss getting started initial setup

docs: Improve the documentation so it's easier to not miss getting started initial setup

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_NestedPage1.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Uno.Toolkit.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Wasm/Uno.Toolkit.Samples.Wasm.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Uno.Toolkit.WinUI.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Wasm/Uno.Toolkit.WinUI.Samples.Wasm.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Uno.Toolkit.WinUI.Samples.iOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

chore: bump packages

---

doc/controls-styles.md
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_DataContext_NestedPage1.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_Primary.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_Primary.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.v2.xaml
src/library/Uno.Toolkit.Material/Generated/mergedpages.winui.v2.xaml
src/library/Uno.Toolkit.Material/MaterialToolkitResourcesV2.cs
src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

feat: Add PrimaryNavigationBarStyle

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml

GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Figma/issues/630
- Bugfix
Fix Chips icon alignment and size

fix: Chips icon alignment and size

---

doc/controls-styles.md
doc/helpers/StatusBar-extensions.md
doc/toc.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/IExitNestedSampleHandler.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/StatusBarSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/StatusBarSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/StatusBarSample_NestedPage1.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/StatusBarSample_NestedPage1.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/StatusBarSample_NestedPage2.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/StatusBarSample_NestedPage2.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Entities/SourceSdk.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/Uno.Toolkit.UI/Behaviors/StatusBar.Android.cs
src/Uno.Toolkit.UI/Behaviors/StatusBar.cs
src/Uno.Toolkit.UI/Behaviors/StatusBar.iOS.cs
src/Uno.Toolkit.UI/Behaviors/StatusBarForegroundTheme.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs

GitHub Issue (If applicable): unoplatform/private#317
- Feature
Provides two attached properties on `Page` to controls the visual of the status bar on mobile platforms.

feat: StatusBar extensions

---

doc/controls/TabBarAndTabBarItem.md
src/library/Uno.Toolkit.Material/Generated/mergedpages.winui.v2.xaml

https://github.com/unoplatform/uno/discussions/9187

docs: Address style key changes in migration

---

doc/controls-styles.md
doc/helpers/Input-extensions.md
doc/helpers/control-extensions.md
doc/toc.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ControlExtensionsSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ControlExtensionsSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/InputExtensionsSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/InputExtensionsSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/Uno.Toolkit.UI/Behaviors/ControlExtensions.cs
src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs

GitHub Issue (If applicable): closes #280, closes #282
- Feature

feat: ControlExtensions and InputExtensions 

---

src/Uno.Toolkit.UI/Behaviors/ControlExtensions.cs
src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs

add log warnings & missing xml documentation
re: https://github.com/unoplatform/uno.toolkit.ui/pull/287#pullrequestreview-1079183887

chore: warning & xml documentation

---

doc/controls/AutoLayoutControl.md
doc/toc.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

Close https://github.com/unoplatform/Uno.Figma/issues/337
- Feature
- Autolayout children Height and Width could't be set. 
- No Autolayout in sample app
- Autolayout children Height and Width can be set. 
- Autolayout in sample app

feat(AutoLayout): add Height and Width support and update documentation.

---

doc/getting-started.md

GitHub Issue (If applicable): No Issue
The link  https://github.com/unoplatform/Uno.Themes/blob/master/doc/getting-started.md#customization present at the end of the page lead to a 404 page.
The link https://platform.uno/docs/articles/external/uno.themes/doc/material-getting-started.html#customization lead to the customization section of the external site of the Uno.Material theme. That section gives instruction on changing the default color palette or the font family.

doc: Fix link to customization

---

doc/controls/AutoLayoutControl.md
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

https://github.com/unoplatform/Uno.Figma/issues/550
- Feature
- Children have the Z order according to the order they are added
- Add IsReverse  property to AutoLayout that reverse the Z order
This property emulate the Canvas Stacking option for AutoLayout  in figma 

feat(AutoLayout): add IsReverse Property

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

- Bugfix
- Independent layout could not take the place needed inside his parent
- Add a check for a extra empty grid for the Independent layout to span correctly

fix(AutoLayout): make sure the indenpendent layout can span all over his parent

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Uno.Toolkit.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Tizen/Uno.Toolkit.Samples.Skia.Tizen.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Wpf.Host/Uno.Toolkit.Samples.Skia.Wpf.Host.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Wpf/Uno.Toolkit.Samples.Skia.Wpf.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Wasm/Uno.Toolkit.Samples.Wasm.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Uno.Toolkit.WinUI.Samples.Skia.Gtk.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.UWP/Uno.Toolkit.WinUI.Samples.UWP.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Wasm/Uno.Toolkit.WinUI.Samples.Wasm.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Uno.Toolkit.WinUI.Samples.iOS.csproj
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

GitHub Issue (If applicable): N/A
Currently there are dependencies to prerelease or dev versions of packages
Dependencies are to stable packages where possible

chore(deps): Bump to stable dependencies

---

doc/controls-styles.md
doc/helpers/VisualStateManager-extensions.md
doc/toc.yml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/VisualStateManagerExtensionsSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/VisualStateManagerExtensionsSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Entities/SampleCategory.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems
src/Uno.Toolkit.UI/Behaviors/VisualStateManagerExtensions.cs
src/Uno.Toolkit.UITest/Behaviors/Given_VisualStateExtensions.cs
src/Uno.Toolkit.UITest/TestBase.cs

GitHub Issue (If applicable): resolved #306, resolved #338
- Feature
added attached properties to manipulate VisualState
fixed TakeScreenshot filename sanitization

feat: VisualStateExtensions

---

doc/helpers/VisualStateManager-extensions.md
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/VisualStateManagerExtensionsSamplePage.xaml
src/Directory.Build.props
src/Uno.Toolkit.UI/Behaviors/VisualStateManagerExtensions.cs
src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.v1.xaml
src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.v2.xaml

ci: add xamarin.mac workaround

---

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

- Bugfix
- AutoLayout independent layout was not working with PrimaryAxisAlignment center or end
- PrimaryAxisAlignment center or end behave as wanted with independant layout

fix(AutoLayout): Support primaryAxisAlignment with independent layout

---

src/Uno.Toolkit.UI/Controls/LoadingView/CompositeLoadableSource.cs
src/Uno.Toolkit.UI/Controls/LoadingView/LoadableSource.cs
src/Uno.Toolkit.UI/Extensions/DispatcherQueueExtensions.cs

GitHub Issue (If applicable): #355
- Bugfix
- Code cleanup
Uses Dispatcher which is null on some platforms
Uses DispatcherQueue
*Note: When reviewing, hide whitespace changes - the move to file scoped namespace results in a lot of white space changes

fix: Switch to DispatcherQueue

---

samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Properties/AndroidManifest.xml
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj
src/crosstargeting_override.props.sample
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

Uno 4.6.0 will drop monoandroid11.0

chore: bump to monoandroid12.0

---

build/workflow/pipeline.yml
build/workflow/scripts/macos-build.sh
build/workflow/stage-build.yml
build/workflow/stage-uitests-android.yml
build/workflow/stage-uitests-ios.yml
build/workflow/stage-uitests-wasm.yml

Avoid accidentally disabling net6.0 target frameworks

ci: include net6 builds

---

doc/controls/AutoLayoutControl.md
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.xaml

- Feature
- Auto Layout Padding behave like any other control
- Auto Layout Padding behave like figma Auto Layout

feat(Auto Layout): Make Padding to behave like figma Auto Layout

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

-  gridIndexOffSet in AutoLayout was not properly increment.
- gridIndexOffSet in AutoLayout properly increment.

fix(AutLayout): gridIndexOffSet was not properly increment.

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

- Bugfix
- When spacing were superior to padding it could cause the control to not work properly 
- Spacing and padding should behave as expeted

fix(AutoLayout): fixing issue when spacing was superior to padding causing a invalid GridLenght.

---

src/Directory.Build.props
src/PlatformItemGroups.props
src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj
src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj

add support for SupportedOSPlatformVersion, centralize globbing

chore: add platform props

---

nuget.config
src/Directory.Packages.props
src/PlatformItemGroups.props
src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj
src/Uno.Toolkit.sln
src/library/Uno.Toolkit.WinUI.Markup/AssemblyInfo.cs
src/library/Uno.Toolkit.WinUI.Markup/Uno.Toolkit.WinUI.Markup.csproj

feat: Add Toolkit Markup Library

---

nuget.config

build: Use single feed

---

.github/workflows/azure-static-webapp.yml

ci: Don't fail Azure deployment for PR from forks

---

src/library/Uno.Toolkit.WinUI.Markup/Uno.Toolkit.WinUI.Markup.csproj

build: Avoid MSBuild warning about using different MSBuild.Sdk.Extras versions

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

- Feature
- Figma Hug behavior was not supported
- Padding behavior when hug was not supported 
- Figma Hug behavior is supported
- Padding behavior when hug is supported 

feat(AutoLayout): Add hug support and hug padding behavior.

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

space between was not properly disable in case of stretch children
Using offset to set the right grid definition fixing the issue

fix(autolayout): add the offsetgrid count correctly

---

src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs

GitHub Issue (If applicable): 
closes https://github.com/unoplatform/uno.chefs/issues/142
- Bugfix
Windows app crashes when hitting on enter on Login and Search Page.

fix(winui): when attempting to dismiss keyboard

---

src/Directory.Build.props
src/PlatformItemGroups.props

build: Simplify Directory.Build.props and PlatformItemGroups.props

---

doc/toc.yml

docs: Fix VisualStateManager-extensions.md href in ToC

---

src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs
src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml

closes https://github.com/unoplatform/uno.toolkit.ui/issues/509
- Bugfix

fix: Remove fixed height for TabBar

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml

related https://github.com/unoplatform/uno.chefs/issues/414

fix: update tabbaritem font size to match design

---

src/Uno.Toolkit.RuntimeTests/Tests/SelectorExtensionsTests.cs
src/Uno.Toolkit.UI/Behaviors/SelectorExtensions.cs

GitHub Issue (If applicable): closes #403

fix: Fix SelectorExtensions not updating NumberOfPages on Selector load

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/Divider.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/_Common.xaml

GitHub Issue (If applicable): #https://github.com/unoplatform/private/issues/331
Changed implicit/explicit default style keys for Divider, NavigationBar and AppBarButton.
Tested using this code

refactor: check for missing explicit and implicit v2 styles

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/_Common.xaml

https://github.com/unoplatform/Uno.Figma/pull/1634

feat: Add implicit Chip style

---

src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs
src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs

GitHub Issue (If applicable): Closes #562

fix(TabBar): Don't call SelectedIndex setter with the same old value to let it work with bindings

---

Directory.Build.props
samples/Directory.Build.props
src/Directory.Build.props

build: Disable XAML fuzzy matching

---

src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs

Related to https://github.com/unoplatform/uno.toolkit.ui/issues/685

chore: Lambda function call instance method

---

doc/controls/ShadowContainer.md

We have the docs.
Simple improvement for easier reading and understanding.

[ShadowContainer][Docs] Simple improvement for easier reading and understanding

---

samples/Directory.Packages.props
src/Directory.Packages.props
src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj

- Chore: update Material and MUX

chore: update Material and MUX

---

samples/Directory.Packages.props
src/Directory.Packages.props

- Chore: legacy update Material and MUX

chore: legacy update Material and MUX

---

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs

GitHub Issue (If applicable): #660
- Other... Please describe: Add runtime test
No runtime test for collapsed visibility 
Runtime test for collapsed visibility

chore(autolayout): add test for collapsed

---

.github/pull_request_template.md

- Other: PR Template update
Update pull_request_template.md to add docs in PR Checklist

chore: Update pull_request_template.md to add docs in PR Checklist

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters/HexToColorConverter.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowCollection.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Properties.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs

When I tried to fix the conflicts on #704 I did a bad rebase and lost the reference, so I'm opening this PR doing the backport.

Backport from PR 696

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.Navigation.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml.cs

GitHub Issue (If applicable): #n/a
Annoying "Unchanged files with check annotations" in every pr...
It is no more.

chore: address github pr check warnings

---

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/Shadow.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowCollection.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Properties.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs
src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs
src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs

Reverts unoplatform/uno.toolkit.ui#737 AKA dual shadow impl

Revert "fix(shadows): background theming issue"

---

.github/workflows/azure-static-webapp.yml

Update to Toolkit WinUI samples

chore: Update to Toolkit WinUI samples

---

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs

fix(ShadowContainer): Properly invalidate on shadows collection changed

---

src/Uno.Toolkit.RuntimeTests/Tests/ShadowContainerTests.cs
src/Uno.Toolkit.Skia.WinUI/AssemblyInfo.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowsCache.cs

Closes #791
- Other... Please describe: Test
There is no test for that
Added a new test

test: Added Test for ShadowContainer re-layout issue

---

doc/controls/ShadowContainer.md

chore: Add missing title for ShadowContainer.md

chore: Add missing title for ShadowContainer.md

---

src/Directory.Packages.props

Update Markup libraries

---

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs

chore(autolayout): removed sealed for Xaml2Csharp

---

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayoutExtensions.cs

- Feature
- Max size does not work
- Max size does work

feature(autolayout): add max size support

---

doc/getting-started.md
doc/lightweight-styling.md
doc/material-getting-started.md
src/library/Uno.Toolkit.WinUI.Markup/MarkupInit.cs
src/library/Uno.Toolkit.WinUI.Material.Markup/MarkupInit.cs

closes https://github.com/unoplatform/uno.toolkit.ui-private/issues/5
Update docs for C# Markup
re-work markup init helpers

Toolkit Markup init and docs

---

src/Uno.Toolkit.RuntimeTests/Helpers/ImageAssertHelper.cs
src/Uno.Toolkit.RuntimeTests/Tests/ShadowContainerTests.cs
src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs
src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml
src/Uno.Toolkit.UITest/Controls/TabBar/Given_TabBar.cs
src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml

chore: fix failing tests

---

src/Uno.Toolkit.UI/Controls/Card/Card.Properties.cs
src/Uno.Toolkit.UI/Controls/CardContentControl/CardContentControl.cs

fix: Shadow colors are no longer solid black on Android

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/Card.xaml

[#920](https://github.com/unoplatform/uno.toolkit.ui/issues/920)

fix: Card Border

---

doc/controls/NavigationBar.md

https://github.com/unoplatform/uno/pull/14688
- Bugfix
[Teams](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1701463587295?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1701463587295&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1701463587295)

docs: Improve FAQ searchability

---

src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs

fix: Make ResponsiveHelper public

---

build/workflow/stage-build-packages.yml
src/Uno.Toolkit-packages.slnf

skip building ui/runtime tests & sample app for package build job

build: packages only build

---

doc/controls/AutoLayoutControl.md
doc/controls/DrawerFlyoutPresenter.md
doc/lightweight-styling.md
doc/material-migration.md

docs: General fixes and small improvements

---

doc/toc.yml

docs: add splash screen to toc

---

doc/helpers/ancestor-itemscontrol-binding.md
doc/helpers/itemsrepeater-extensions.md
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ItemsRepeaterExtensionsSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ItemsRepeaterExtensionsSamplePage.xaml.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.Properties.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters/EnumerableConverter.cs
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Styles/SamplePageLayout.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems

- Other... Please describe: more samples.
expanded the documentation and added samples for ItemsRepeater-extensions and ItemsControl-binding.

docs: update samples for ItemsRepeater-ext and ItemsControl-binding

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml

Related to:
https://github.com/unoplatform/Uno.Themes/issues/1248
What kind of change does this PR introduce? 
- Bugfix 

Removing Tint

---

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerFlyoutSamplePage.xaml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/CupertinoBottomBarSampleNestedPage.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v1/BottomTabBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v1/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v1/TopTabBar.xaml

GitHub Issue (If applicable): #924

Replace VisibleBoundsPadding to SafeArea

---

doc/controls/TabBarAndTabBarItem.md
src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
src/library/Uno.Toolkit.WinUI.Markup/Theme/TabBar.cs

fix(tabbar): add surface tint layer to material bottom/vertical navigation tabbar

---

samples/Directory.Packages.props
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs
src/Directory.Packages.props
src/Uno.Toolkit.UI/Behaviors/TabBarSelectorBehavior.Properties.cs
src/Uno.Toolkit.UI/Behaviors/VisualStateManagerExtensions.cs
src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.NetStandard.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.Android.cs
src/Uno.Toolkit.UI/Controls/TabBar/TabBarListPanel.cs
src/Uno.Toolkit.UI/Helpers/ImageHelper.iOS.cs
src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs
src/library/Uno.Toolkit.Cupertino/Converters/InflateDimensionConverter.cs
src/library/Uno.Toolkit.Cupertino/Styles/Controls/BottomTabBar.xaml
src/library/Uno.Toolkit.Cupertino/Styles/Controls/SegmentedControl.xaml

Warning that there's a new version of the net analyzers
Updated to latest analyzers(v8.0.0) and fixed build errors

chore: Updated analysers to v8 and fixed all errors (from new analyzers)

---

README.md
doc/controls-styles.md
doc/controls/AutoLayoutControl.md
doc/controls/CardAndCardContentControl.md
doc/controls/ChipAndChipGroup.md
doc/controls/Divider.md
doc/controls/DrawerControl.md
doc/controls/DrawerFlyoutPresenter.md
doc/controls/ExtendedSplashScreen.md
doc/controls/LoadingView.md
doc/controls/NavigationBar.md
doc/controls/ResponsiveView.md
doc/controls/SafeArea.md
doc/controls/ShadowContainer.md
doc/controls/TabBarAndTabBarItem.md
doc/cupertino-getting-started.md
doc/getting-started.md
doc/helpers/FlipView-extensions.md
doc/helpers/Input-extensions.md
doc/helpers/Selector-extensions.md
doc/helpers/StatusBar-extensions.md
doc/helpers/TabBarItem-extensions.md
doc/helpers/VisualStateManager-extensions.md
doc/helpers/ancestor-itemscontrol-binding.md
doc/helpers/command-extensions.md
doc/helpers/itemsrepeater-extensions.md
doc/helpers/resource-extensions.md
doc/helpers/responsive-extension.md
doc/material-getting-started.md
doc/material-migration.md

docs: Improve documentation

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

fix: Navbar Icons sizing

---

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayoutExtensions.cs

Fixes https://github.com/unoplatform/uno.toolkit.ui/issues/1034

fix: Fixed Axis Alignments (both primary and counter) when children is not filling space

---

src/Directory.Packages.props

chore(deps): Update Uno to 5.0.154 (fixes nested classes issue on Android)

---

doc/controls/SafeArea.md
doc/helpers/StatusBar-extensions.md

GitHub Issue (If applicable): internal

chore: Add Tech Bites video for SafeArea and StatusBar

---

doc/material-getting-started.md

﻿## PR Type
Update Material Toolkit resources links with proper aka links

docs: Update Material Toolkit resources links

---

doc/controls/DrawerFlyoutPresenter.md
doc/controls/NavigationBar.md
doc/controls/ResponsiveView.md

GitHub Issue (If applicable): internal

docs: Reference Tech Bites videos in docs pt.2 

---

doc/controls/ResponsiveView.md

- Bugfix
Referenced videos got accidentally inverted. 

docs: Fix inverted ResponsiveView Tech Bite videos

---

doc/controls/ExtendedSplashScreen.md
samples/Directory.Packages.props
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Mobile/Android/AndroidManifest.xml
samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml
samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Mobile/Android/AndroidManifest.xml
src/Directory.Packages.props
src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Android.cs
src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.cs
src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.cs
src/Uno.Toolkit.UI/Extensions/SizeExtensions.cs
src/Uno.Toolkit.UI/Resources/values/Styles.xml
src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj
src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj

fixes #1054 
Left is API 34, Right is API 28

feat(ExtendedSplashScreen): add android 12 splashscreen support

---

src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs

fixes https://github.com/unoplatform/uno.toolkit.ui/issues/1066

fix: register events when navbarpresenter owner is set

---

src/Directory.Build.props
src/Uno.Toolkit.UI/build/Package.targets
src/library/Uno.Toolkit.Cupertino/build/Package.targets
src/library/Uno.Toolkit.Material/build/Package.targets
src/library/Uno.Toolkit.WinUI.Markup/build/Package.targets
src/library/Uno.Toolkit.WinUI.Material.Markup/build/Package.targets

- n/a
- Feature
Adding support for Implicit Namespaces

Adding support for Implicit Namespaces

---

src/Uno.Toolkit.RuntimeTests/Tests/ShadowContainerTests.cs
src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16049

fix: Workaround ActualHeight bug for ShadowContainer

---

build/workflow/stage-determine-changes.yml

ci: Adjust stage-determine-changes.yml

---

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs

GitHub Issue (If applicable): private issue
- Bugfix

fix: Make the `DrawerFlyoutPresenter` parent requirement more loose

---

doc/controls/TabBarAndTabBarItem.md

Add TechBites video playlist for TabBar and TabBarItem

docs: Add TechBites video playlist for TabBar and TabBarItem

---

src/Uno.Toolkit.RuntimeTests/Uno.Toolkit.RuntimeTests.WinUI.csproj

build: Set RuntimeIdentifiers in runtime tests

---

doc/helpers/Input-extensions.md
doc/helpers/command-extensions.md

GitHub Issue (If applicable): internal 25, 30

docs: Reference TechBites videos pt.4

---

doc/helpers/resource-extensions.md

[Docs] Update resource-extensions.md

---

src/PlatformItemGroups.props

build: Remove explicit `TargetPlatformVersion`

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.Android.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno.toolkit.ui/issues/1178

fix: ContentTemplate shouldn't be passed down to a NativeNavigationBarPresenter

---

src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs
src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs

GitHub Issue (If applicable): #n/a
- Bugfix
calling SetOverrideSizeProvider throws NullRefException if the ResponsiveHelper was never initialized.
^ no more.

fix(responsive): SetOverrideSizeProvider throwing

---

doc/helpers/FlipView-extensions.md

GitHub Issue (If applicable): #1207

docs: FlipViewExtensions - fixing usage example

---

doc/helpers/ancestor-itemscontrol-binding.md

GitHub Issue (If applicable): closes #1206

docs: AncestorBindings- fixing example code

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

GitHub Issue (If applicable): https://github.com/unoplatform/uno.hotdesign/issues/2225
- Bugfix
Fixing a typo

fix: navigationbar foreground typo

---

src/Uno.Toolkit.UITest/Controls/SafeArea/Given_SafeArea.cs

related https://github.com/unoplatform/uno.toolkit.ui/issues/1232

chore: disable safearea ios test

---

doc/lightweight-styling.md

GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/504

chore: Update broken LightweightStyling link

---

build/workflow/scripts/ios-uitest-run.sh

Ensure we don't fail with a timeout when waiting for the simulator

ci: fix ios test run

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/CardContentControl.xaml

fix: background setter

---

build/workflow/pipeline.yml
build/workflow/stage-build-winappsdk.yml
src/Uno.Toolkit.RuntimeTests/Uno.Toolkit.RuntimeTests.WinUI.csproj

GitHub Issue (If applicable): Follow-up to #1157 

ci: Build WinAppSDK

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.Android.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs

closes #1272
closes https://github.com/unoplatform/uno.toolkit.ui/issues/1273

fix: navBar initialization-Android & iOS

---

src/Uno.Toolkit.UI/Controls/ZoomContentControl/ZoomContentControl.cs
src/Uno.Toolkit.UI/Extensions/RectExtensions.cs

GitHub Issue (If applicable): #1303
- Bugfix
- Feature

fix(zcc): add support for negative canvas coord space

---

src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18545

fix(AppBarButtonRenderer): only subscribe to AppBar.Icon.UriSource if Icon is a BitmapSource

---

src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

fixes https://github.com/unoplatform/Uno.Themes/issues/1462

chore: navbar appbarbutton height

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

fix: don't allow Content to flow to NativeNavigationBarPresenter

---

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.chefs/issues/1442
- Bugfix

fix: Support padding and `SafeArea` in `NavigationBar` on Skia

---

src/CrossTargeting.props
src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml
src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml

closes https://github.com/unoplatform/uno.chefs/issues/1489

fix: NavigationBar padding support for CommandBar

---

src/Uno.Toolkit.UI/Controls/TabBar/TabBarSelectionIndicatorPresenter.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/913

fix: tabbar sliding indicator selection

---

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1146
[flyout-2.webm](https://github.com/user-attachments/assets/1084399f-bff6-4db7-9b46-2a8e35fa5d38)

fix: drawerFlyout flicker

---

src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs

GitHub Issue (If applicable): closes unoplatform/uno-private#1252
- Bugfix
SafeArea applied within DrawerFlyout does not have its margin/padding calculated properly while the flyout during its opening animation.
^ the animation offset is now accounted for.

fix(SafeArea): bounds calculation when midst DrawerFlyout animation

---

src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveExtensionsTests.cs
src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno.chefs/issues/1644
- Bugfix
When un-minimizing a window on Desktop/Wasm the initial size is resolved to 0px x 0px.
We can treat a width or height of 0px as invalid.

fix: minimizing with responsive extensions

---

doc/helpers/Input-extensions.md
doc/toc.yml
doc/uno-toolkit-migration.md
src/Directory.Packages.props
src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs
src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.cs

GitHub Issue (If applicable): closes #1387

feat!: switch InputExtensions.ReturnType to InputReturnType

---

version.json

Bump version to 8.0 for breaking change introduced by https://github.com/unoplatform/uno.toolkit.ui/pull/1417

chore: bump to 8.0

---

src/Uno.Toolkit.RuntimeTests/Tests/SafeAreaTests.cs
src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.cs
src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs

GitHub Issue (If applicable): closes unoplatform/uno#20446
- Bugfix
Multiple layered SafeArea tend to take multiple layout passes to settle doen to a stabilized configuration. SafeArea are applied in the FE::Load order, from inner-most to outer-most. And, then the inner re-adjusts to the outer ones changes...
Inner SafeAreas applications are blocked if an unapplied outer SafeArea existing. And, they are later applied during UIE::LayoutUpdated if applicable.
removed previous attempt #1415, as this approach has better coverage.

refactor(safearea): improve layered safe-areas performance

---

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs

GitHub Issue (If applicable): closes #1436
- Bugfix
On native renderer setup, the drawer flyout doesn't play its opening animation when first opened.
^ no more.

fix(drawerflyout): missing initial open animation
