unoplatform/uno.toolkit.ui

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj
- Android project file changes
Remove the target that will force the generation of the APK as it's not needed anymore and as it causes issues to deploy on Android with latest VS 2022 Prev 17.1.0 Preview 1.0 and 1.1
=> chore(Android): Remove the target that will force the generation of the APK as it's not needed anymore

src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.Mobile.xaml
GitHub Issue (If applicable): #76 
- Bugfix
Top half of Fab TabBarItem is not clickable on iOS / Android
The Fab TabBarItem is clickable entirely on all platforms
=> fix(iOS/Android): Top half of Fab TabBarItem is not clickable

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_ModalPage2.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_NestedPage1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_NestedPage2.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.Native.xaml, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs, src/Uno.Toolkit.UITest/Constants.cs, src/Uno.Toolkit.UITest/NavigationBar/Given_NavigationBar.cs, src/library/Uno.Toolkit.Cupertino/Generated/mergedpages.uwp.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/BottomTabBar.Mobile.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/BottomTabBar.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/SegmentedControl.Mobile.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/SegmentedControl.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/SlidingSegmentedControl.Mobile.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/SlidingSegmentedControl.xaml, src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj, src/library/Uno.Toolkit.Cupertino/xamlmerge.props, src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Base.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.Mobile.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/NavigationBar.xaml, src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj, src/library/Uno.Toolkit.Material/xamlmerge.props
relates to: https://github.com/unoplatform/uno/issues/3892
relates to: https://github.com/unoplatform/uno/issues/6717
relates to: https://github.com/unoplatform/uno/issues/7803
- Bugfix
**As of iOS 13, the preferred method for styling the UINavigationBar and its components is by using the [UINavigationBarAppearance](https://developer.apple.com/documentation/uikit/uinavigationbarappearance) and [UIBarButtonItemAppearance](https://developer.apple.com/documentation/uikit/uibarbuttonitemappearance) APIs.**
The Native UINavigationBar wasn't truly having its background set. Instead, the Border that wraps the NativeNavigationBarPresenter is what determined was displaying the background color. This …
=> fix(NavigationBar):  Move to UINavigationAppearance APIs, fix unapplied background color

src/library/Uno.Toolkit.Material/Styles/Controls/TopTabBar.Base.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/TopTabBar.Mobile.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/TopTabBar.xaml
closes #109
- Bugfix
SelectionIndicator could become larger than the tabs items
SelectionIndicator maintains same width as TabBarItems
=> fix(TabBar): Remove MinWidth from TabBarSelectionIndicator

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_DataContext_NestedPage1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_DataContext_NestedPage1.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.Android.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs, src/Uno.Toolkit.UITest/NavigationBar/Given_NavigationBar.cs
closes https://github.com/unoplatform/uno/issues/3712
Android FluentTheme AppBarButton does not render its Content: https://github.com/unoplatform/uno/issues/7970
MaterialAppBarButton style DataContext issue: https://github.com/unoplatform/Uno.Gallery/issues/336
- Bugfix
The following XAML, where NavigationBar's Content and AppBarButton's Content is a TextBlock would not render on the native navigation bars.
```xml
<utu:NavigationBar AutomationProperties.AutomationId="Page1DataContextNavBar"
MainCommandMode="Action">
<utu:NavigationBar.Content>
<Grid VerticalAlignment="Center"
ios:HorizontalAlignment="Center">
<TextBlock ios:TextAlignment="Center"
Foreground="Black"
Text="{Binding ViewModelName}" />
</Grid>
</utu:NavigationBar.Content> …
```
=> NavigationBar Support for FrameworkElement-based Content for NavBar/AppBarButton

src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.xaml, src/library/Uno.Toolkit.Material/Generated/mergedpages.winui.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/_Common.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/344
- Bugfix
UWP/Winui heads start properly
=> fix(uwp): Include material fonts resources in toolkit resources

src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.Mobile.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/TopTabBar.Mobile.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/TopTabBar.xaml
- Bugfix
Some Material styles for [Bottom/Top]TabBar were not prefixed with `mobile:` or `not_mobile:`. Causing issues with the xaml merge
=> fix(TabBar): use mobile/not_mobile prefixes for Top/Bottom TabBars

src/Uno.Toolkit.UI/Helpers/SystemThemeHelper.cs
GitHub Issue (If applicable): #n/a
- Bugfix
IsAppInDarkMode is always based on os theme, ignoring the app theme.
ToggleApplicationTheme fails to work after the first time, due its reliance on the above method.
=> fix(SystemThemeHelper): darkmode detection logic

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NavigationBarSample_DataContext_NestedPage1.xaml, src/library/Uno.Toolkit.Material/Generated/mergedpages.uwp.xaml, src/library/Uno.Toolkit.Material/Generated/mergedpages.winui.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/BottomTabBar.xaml
GitHub Issue (If applicable): #205 
- Bugfix
Uwp sample app crashes on launch
- For the MaterialBottomTabBarStyle : `Error HRESULT E_FAIL has been returned from a call to a COM component.`
- For the NavigationBarSample_DataContext_NestedPage1
Uwp sample app doesn't crash on launch
- Fixed by using a proper GridLength resource for MaterialBottomTabBarHeight for the MaterialBottomTabBarStyle.
- Fixed NavigationBar content for NavigationBarSample_DataContext_NestedPage1
=> fix: Uwp sample app crashes on launch

src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj, src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj
=> fix: Make sure WinUI version of Toolkit Themes include/exclude the mobile and not_mobile XAML namespaces

src/library/Uno.Toolkit.Material/Styles/Controls/v1/NavigationBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
- Bugfix
On Windows, having more than one NavigationBar within the visual tree will cause a crash
This is because of the SymbolIcon: On Windows, no IconElement derived classes (besides BitmapIcon) can be used as a StaticResource and placed multiple times in the visual tree.
https://github.com/microsoft/microsoft-ui-xaml/issues/1494
Don't crash
=> fix: Remove use of SymbolIcon in NavBar styles

src/library/Uno.Toolkit.Material/Styles/Controls/v2/BottomTabBar.xaml
closes: https://github.com/unoplatform/Uno.Figma/issues/606
background is still tinted a bit because the colors update hasnt merged yet
=> fix: Fix Material BottomTabBar selection indicator and colors

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
Fix error that was setting the default AppBarButton within NavigationBar to the improper foreground/background
Adjust Height of XAML-based NavBar to 64
=> fix(NavigationBar): improperly setting foreground/background to appbarbutton

src/library/Uno.Toolkit.Material/Styles/Controls/v2/BottomTabBar.xaml
closes https://github.com/unoplatform/Uno.Figma/issues/689
Adjust padding values and icon size to match Figma file
=> fix(BottomTabBar): Adjust padding of BottomTabBarItems

doc/controls-styles.md, doc/controls/DrawerFlyoutPresenter.md, doc/toc.yml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerFlyoutSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerFlyoutSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.Properties.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.xaml, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs, src/Uno.Toolkit.UI/ToolkitResources.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#372
- Feature
Add `FlyoutPresenterStyle`s that enable gesture support for flyouts.
The uno.ui version needs to be bumped for Manipulation events to have the proper e.OriginalSource.
=> Drawer Flyout support

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Styles/Application/Colors.xaml
GitHub Issue (If applicable): closes #267
- Bugfix
Samples app main content background doesnt toggle with theme
Samples app main content background will toggle with theme
n/a
=> fix: sample app background not toggling with theme

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs
GitHub Issue (If applicable): closes #277
- Bugfix
fixed multiple instances of crash related to DrawerFlyout
=> DrawerFlyout bugfixes

src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs
closes #298
PR Type
Bugfix
What is the current behavior?
Converters for NavigationBar Foreground/Background or any of its AppBarButton properties were not working
What is the new behavior?
Converters should now work
=> fix(NavigationBar): Avoid null BitmapIcon.UriSource

doc/controls/DrawerFlyoutPresenter.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerFlyoutSamplePage.xaml.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.Properties.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.xaml
GitHub Issue (If applicable): resolved #311
- Bugfix
DrawerFlyoutPresenter was in the wrong namespace.
is in the right place.
=> fix: DrawerFlyoutPresenter namespace

src/crosstargeting_override.props.sample
- Bugfix
invalid crosstargeting_override.props syntax, and the project wont build
project can now build
=> fix: invalid crosstargeting_override

src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarHelper.iOS.cs
GitHub Issue (If applicable): resolved: #307
- Bugfix
When navigating to an external view/controller and back, the NavigationBar re-initializes with the UIViewController (native concept) with the wrong instance of NavigationBar (toolkit control). This desync prevents the NavigationBar from updating.
^ not happening anymore.
=> fix: NavigationBar desync in certain scenario

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/SafeAreaSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/SafeAreaSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_ModalPage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_ModalPage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs, src/Uno.Toolkit.UITest/Controls/SafeArea/Given_SafeArea.cs, src/Uno.Toolkit.UITest/TestBase.cs
closes https://github.com/unoplatform/nventive-private/issues/412
- Bugfix
SafeArea calculates improper offsets when the control is within a native iOS Modal window. We were using `TransformToVisual` relative to `Windows.Current.Content` which results in an offset of X=16, Y=47 since the Window.Content (white background) is no longer at position 0,0 while a modal (red background) is being displayed
Use `TransformToVisual(null)` to ensure that the root of the XAML tree is used for the transformation
=> fix(SafeArea): Ensure the root of the XAML tree is used to compute relative bounds of SafeArea control/owner

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.cs
- Bugfix
NavigationBar was not hooking onto SystemNavigationManager.BackRequested for Uno platforms that are targeting the WinUI APIs
NavigationBar now hooks onto SystemNavigationManager.BackRequested for Uno platforms that are targeting the WinUI APIs
=> fix: WinUI NavBar back button support

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_ModalPage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_ModalPage.xaml.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.Properties.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v1/NavigationBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
closes https://github.com/unoplatform/uno/issues/9494
- Bugfix
Setting the `NavigationBar`'s Content to a `FrameworkElement` instead of just a string results in a crash on Windows 
Adding `NavigationBarContent` property on the `NavigationBarPresenter` and TemplateBinding that to the `CommandBar`'s `ContentProperty` works around the issue and avoid the crash.
=> fix(NavigationBar): Add NavigationBarContent property

doc/helpers/VisualStateManager-extensions.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/VisualStateManagerExtensionsSamplePage.xaml, src/Uno.Toolkit.UI/Behaviors/VisualStateManagerExtensions.cs
GitHub Issue (If applicable): #306
refactor: VisualStateManagerExtensions.OverrideStates -> States
=> refactor: VisualStateManagerExtensions.OverrideStates -> States

src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.cs
GitHub Issue (If applicable): #348
- Bugfix
Given:
```xml
<ChipGroup ItemsSource="{Binding Items}" SelectionMode="Multiple" SelectionMemberPath="IsSelected" />
```
```cs
public IEnumerable Items { get; } = Enumerable.Range(0, 9).Select(x => new { IsSelected = x % 2 == 0 }).ToArray();
```
None of the resulting chips are selected.
^ will work.
=> fix(ChipGroup): SelectionMemberPath overwritten by SelectionItem(s)

doc/controls/LoadingView.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/LoadingViewSample.xaml, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.cs, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.xaml
GitHub Issue (If applicable): #336
- Feature
No explicit style - applications have to copy entire style instead of just adding LoadingContent (or overriding specific properties)
No LoadingContentTemplate
No TemplateVisualState attributes defining what visual states should exist in the controltemplate
Adds DefaultLoadingView explicit style
Implicit LoadingView style is BasedOn the added DefaultLoadingView style
Added LoadingContentTemplate property
Added TemplateVisualState attribtues for the Loading and Loaded visual states
=> feat: Adding explicit style for LoadingView

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NativeFrameSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NativeFrameSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_MainPage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_MainPage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_Page1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_Page1.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_Page2.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/NativeFrame_Page2.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.iOS/Uno.Toolkit.Samples.iOS.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.iOS/Uno.Toolkit.WinUI.Samples.iOS.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj, src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj, src/Uno.Toolkit.UITest/Controls/NativeFrame/Given_NativeFrame.cs, src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.UI.Cupertino.csproj, src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj, src/library/Uno.Toolkit.Material/Uno.Toolkit.UI.Material.csproj, src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj
closes https://github.com/unoplatform/uno.toolkit.ui/issues/346
- Bugfix
Manually editing backstack while NativeFramePresenter is being used can lead to blank pages
Properly assign Page instances to viewcontrollers
=> fix(NativeFramePresenter): Allow Frame BackStack manipulation

samples/Directory.Build.props, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Uno.Toolkit.Samples.Skia.Gtk.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Tizen/Uno.Toolkit.Samples.Skia.Tizen.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Wpf.Host/Uno.Toolkit.Samples.Skia.Wpf.Host.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Wpf/Uno.Toolkit.Samples.Skia.Wpf.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Wasm/Uno.Toolkit.Samples.Wasm.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.macOS/Uno.Toolkit.Samples.macOS.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/Uno.Toolkit.WinUI.Samples.Droid.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Uno.Toolkit.WinUI.Samples.Skia.Gtk.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.UWP/Uno.Toolkit.WinUI.Samples.UWP.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Wasm/Uno.Toolkit.WinUI.Samples.Wasm.csproj, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.macOS/Uno.Toolkit.WinUI.Samples.macOS.csproj, src/Directory.Build.props, src/xamarinmac-workaround.targets
This is mainly just housekeeping
- aligning all projects to use the same uno version as the toolkit (which was updated to pick up a fix in uno for the native frame presenter)
- apply the fix for the macos build issue (which is now happening to me locally as well as on CI) to sample projects as well as the core toolkit libraries
=> chore: Aligning uno version reference and fixing macos build issue for local dev

samples/Directory.Build.props
=> fix: restore crosstargeting props for toolkit samples

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/MainActivity.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Properties/AndroidManifest.xml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Droid/Uno.Toolkit.Samples.Droid.csproj, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/SafeAreaSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/SafeAreaSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_SoftInput_Scroll.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/SafeArea_SoftInput_Scroll.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Droid/MainActivity.cs, src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.cs, src/Uno.Toolkit.UI/Controls/SafeArea/SafeArea.xaml, src/Uno.Toolkit.UI/Controls/SafeArea/SafeAreaPresenter.cs, src/Uno.Toolkit.UI/Uno.Toolkit.UI.csproj, src/Uno.Toolkit.UITest/Controls/SafeArea/Given_SafeArea.cs, src/Uno.Toolkit.UITest/Extensions/AppExtensions.cs, src/Uno.Toolkit.sln
relates to https://github.com/unoplatform/uno.toolkit.ui/issues/345
- Bugfix
- Feature
Change the SafeArea control to have a ScrollViewer inside of its ControlTemplate. Encourage use of ScrollViewers when using the SafeArea.SoftInput inset mask. 
Green = "soft" constraint
Red = "hard" constraint
=> feat(SafeArea): Include ScrollViewer in SafeArea template

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
- Bugfix
- Padding in AutoLayout did not support CounterALignment set to stretch from children
- Padding behave properly
=> fix(AutoLayout): CounterAlignment set to Stretch was not supported by the Padding

src/PlatformItemGroups.props
GitHub Issue (If applicable): resolved #396
- Bugfix
UWP Sample crashes with: Cannot locate resource from 'ms-appx:///Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.xaml'.
No crash.
regression from: #383
=> fix(uwp): Cannot locate resource '**/*.xaml'

doc/helpers/control-extensions.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml.cs, src/Uno.Toolkit.UI/Behaviors/CommandExtensions.cs, src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs, src/Uno.Toolkit.UI/Behaviors/ItemsRepeaterExtensions.cs, src/Uno.Toolkit.UI/Extensions/EnumerableExtensions.cs
GitHub Issue (If applicable): re #395
- Feature
n/a
added CommandExtensions.Command support for ItemsRepeater
=> feat: ItemsRepeater support for CommandExtensions

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
- Bugfix
- updateLayout can be call before the verticalAlignment horizantalAlignment and padding are propertly set. 
Happened with xamlreader 
- trigger updateLayout when verticalAlignment horizontalAlignment and padding are changed 
=> fix(autolayout): ensure the layout is recalculated when nesting autolayout

samples/Directory.Packages.props, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
Crash when using M3 NavigationBar styles on Windows, also missing Cupertino.WinUI reference
=> fix: Windows crash

doc/controls/ChipAndChipGroup.md, src/Directory.Packages.props, src/Uno.Toolkit.RuntimeTests/Extensions/ToggleButtonExtensions.cs, src/Uno.Toolkit.RuntimeTests/Helpers/UnitTestUIContentHelperEx.cs, src/Uno.Toolkit.RuntimeTests/Tests/ChipGroupTests.cs, src/Uno.Toolkit.UI/Controls/Chips/Chip.cs, src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.Members.cs, src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.cs, src/Uno.Toolkit.UI/Controls/Chips/ChipSelectionMode.cs
GitHub Issue (If applicable): closes #337, closes #354, re: #356
- reworked `ChipGroup` selection logics
- existing `Single` selection mode now enforces a default selection and prevent the deselection of currently selected item (RadioGroup-like)
> which aligns with the same-named mode in `ListView`
- legacy `Single` selection mode is available as `SingleOrNone` 
- added tests for ChipGroup selection
=> chore: chip selection rework

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/AutoLayoutPage.xaml, src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
GitHub Issue (If applicable): [#1128](https://github.com/unoplatform/Uno.Figma/issues/1128)
- Bugfix
- when in spacebetween the spacing is still use, setting a minimal space between autolayout children
- when spacebetween the spacing will be ignore
- [c] Tested code with current [supported SDKs](../README.md#supported)
- [c] Contains **NO** breaking changes
- [c] Associated with an issue (GitHub or internal)
=> fix(autolayout): When SpaceBetween no spacing

src/Directory.Packages.props
closes https://github.com/unoplatform/uno/issues/10869
Newer version of Uno is needed to avoid build issues when Uno isn't already directly referenced with a newer version
=> Bump Uno 4.6.19 -> 4.6.41

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
GitHub Issue (If applicable): #436
- Bugfix
- when absolute positionned element was under the padding and the padding same size or less than spacing, the element was not properly positionned.
- when PrimaryAxisAlignment="Center" or "End" and one item set to fill and a other item was absolute positionned the autolayout behaved like if not items was fill
- absolute position with margin and padding behave as expected 
- spacebeetween margin fixes
=> fix(autolayout): conflict with padding and spacing vs primary alignment

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters.xaml, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.xaml
GitHub Issue (If applicable): https://github.com/unoplatform/uno.toolkit.ui/issues/290, [#9487](https://github.com/unoplatform/uno/issues/9487)
- Bugfix
Remove unused GestureInterceptorMargin TemplateBinding in the DrawerControl style to fix UWP Sample
re: #290
=> fix: Remove unnecessary GestureInterceptorMargin and TrueToVisible converter in the DrawerControl style to fix UWP Sample

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs
GitHub Issue (If applicable): closes unoplatform/uno.chefs#176
- Bugfix
DrawerFlyout still displaying the LightDismissOverlayBackground after tapping outside
DrawerFlyout does not display the LightDismissOverlayBackground after tapping outside like it should
=> fix: DrawerFlyout still displaying the LightDismissOverlayBackground after tapping outside

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno.chefs/issues/178
- Bugfix
The layout was updated even though the AutoLayout was not loaded
Making sure the AutoLayout is correctly loaded before updating the layout
=> fix(AutoLayout): Making sure the AutoLayout is correctly loaded before updating the layout

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
GitHub Issue (If applicable): #https://github.com/unoplatform/uno.chefs/issues/178
- Bugfix
AutoLayout IsLoaded return false for all platforms except WinUI
(Explain by the fact that the sequence of events is different between Windows and WinUI)
Properly call the UpdateAutoLayout method during the OnLoaded that way IsLoaded is "true" for all platforms at the correct time
=> fix(AutoLayout): Properly call the UpdateAutoLayout method during the OnLoaded

src/Uno.Toolkit.UI/Controls/TabBar/TabBarListPanel.cs
closes https://github.com/unoplatform/uno.chefs/issues/249
=> fix: Adjust measure/arrange for TabBarListPanel

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
Both Content and Icon should follow the Foreground set on TabBarItem
=> fix: TabBarItem Icon should respect templated parent Foreground

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
https://github.com/unoplatform/Uno.Figma/issues/1263
- Bugfix
- Padding didn't behave like in figma for padding and stretch children
- Padding behave as expected when one parent is stretch 
=> fix(autolayout): padding rules when all children are strech

samples/Directory.Packages.props, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj, src/Directory.Packages.props, src/Uno.Toolkit.RuntimeTests/Tests/LeakTest.cs, src/Uno.Toolkit.RuntimeTests/Uno.Toolkit.RuntimeTests.props, src/Uno.Toolkit.UI/Helpers/LinkerAttributes.cs, src/Uno.Toolkit.UI/Uno.Toolkit.WinUI.csproj, src/crosstargeting_override.props.sample, src/library/Uno.Toolkit.Cupertino/Uno.Toolkit.WinUI.Cupertino.csproj, src/library/Uno.Toolkit.Material/Uno.Toolkit.WinUI.Material.csproj, src/library/Uno.Toolkit.WinUI.Markup/Uno.Toolkit.WinUI.Markup.csproj, src/library/Uno.Toolkit.WinUI.Material.Markup/Uno.Toolkit.WinUI.Material.Markup.csproj, src/winappsdk-workaround.targets
- Bugfix
When adding toolkit to a WinUI project, it's necessary to update the frameworkreference - hard for developers to diagnose
Toolkit should be able to be added to winui project without affecting compilation or requiring additional steps
=> fix: Removing framework reference requirement

doc/controls-styles.md, doc/controls/ChipAndChipGroup.md, doc/helpers/itemsrepeater-extensions.md, doc/toc.yml, src/Uno.Toolkit.RuntimeTests/Helpers/XamlHelper.cs, src/Uno.Toolkit.RuntimeTests/Tests/ItemsRepeaterChipTests.cs, src/Uno.Toolkit.UI/Behaviors/ItemsRepeaterExtensions.cs, src/Uno.Toolkit.UI/Controls/Chips/Chip.Members.cs, src/Uno.Toolkit.UI/Controls/Chips/Chip.cs, src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.cs, src/Uno.Toolkit.UI/Helpers/ItemsSelectionHelper.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v1/Chip.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml
GitHub Issue (If applicable): closes #452, closes #395
- Feature
=> feat: add generic selection support for ItemsRepeater

src/PlatformItemGroups.props
Upgrading the SDK forced a higher version which can cause incorrect resolution of assemblies for net6.0-built apps (gallery, specifically).
=> fix: Restore net6.0 compatible TargetPlatformVersion

doc/controls/CardAndCardContentControl.md, src/Uno.Toolkit.UI/Controls/Card/Card.Properties.cs, src/Uno.Toolkit.UI/Controls/Card/Card.cs, src/Uno.Toolkit.UI/Controls/CardContentControl/CardContentControl.cs
GitHub Issue (If applicable): closes #465
- Feature
Card and CardContentControl always respond to pointer & focus events, with no way of disabling this behavior.
This behavior can now be toggled with the new `IsClickable` property on both controls, that is set to `true` by default.
closes unoplatform/uno.chefs#113
=> feat(Cards): add IsClickable property

build/workflow/templates/dotnet-workload-install-windows.yml, samples/Directory.Build.props, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj, src/Directory.Build.targets
GitHub Issue (If applicable): #489 
- Bugfix
Required frameworkreference in winui app when added
Frameworkreference not required
=> fix: Remove frameworkreference

build/workflow/templates/dotnet-workload-install-mac.yml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/TabBarSamplePage.xaml.cs, src/Uno.Toolkit.RuntimeTests/Helpers/UnitTestUIContentHelperEx.cs, src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.Properties.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBarSelectionIndicatorPresenter.Properties.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBarSelectionIndicatorPresenter.cs, src/Uno.Toolkit.UI/Extensions/ItemsControlExtensions.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
closes https://github.com/unoplatform/uno.toolkit.ui/issues/495
TabBarSelectionIndicatorPresenter needs to change MaxSize of the indicator when items in the list are Visibility.Collapsed
- Bugfix
=> fix: TabBar Selection Indicator adapts to collapsed items

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
https://github.com/unoplatform/Uno.Figma/issues/1080
- Bugfix
- When autolayout is in space between mode and a children is independant and have a padding, the padding don't behave as expected. 
This is due to a grid bug when height is discard. the work around is to also set the MaxHeight
- The padding behave as expected is this configuration
=> fix(AutoLayout): remove issue where padding did not behave expectedly

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
=> fix(autolayout): Horizontal padding issue when spacebetween and independant.

src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Behaviors/TabBarSelectorBehaviorState.Others.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBarSelectionIndicatorPresenter.cs
closes https://github.com/unoplatform/uno.toolkit.ui/issues/501
- Bugfix
- Fix for calling ContainerFromIndex with a -1 value
- Fix for TabBarSelectorBehavior interfering with sliding indicator
=> fix: TabBar issues

doc/material-getting-started.md
=> docs: Fix `MaterialToolkitTheme` namespace

src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBarSelectionIndicatorPresenter.cs
closes https://github.com/unoplatform/uno.toolkit.ui/issues/515
=> fix: Handle case when SelectedItem is not of type TabBarItem

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.cs
=> fix(autolayout): padding refactoring

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_Primary.xaml, src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarAutoLayoutPage.xaml, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarAutoLayoutPage.xaml.cs, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarSimplePage.xaml, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarSimplePage.xaml.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarHelper.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/Renderer.cs
relates to https://github.com/unoplatform/uno.chefs/issues/128
- Bugfix
=> fix: Ensure iOS NavigationBar renders when inside of AutoLayout

src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml, src/Uno.Toolkit.UI/Extensions/ItemsControlExtensions.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
Changes for the MinHeight/MinWidth from https://github.com/unoplatform/uno.toolkit.ui/pull/519 accidentally undid the work for the surface tint on TabBars
General TabBar style cleanup 
- Bugfix
=> fix: add tint support back to tabbar, refactor tabbar styles

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_ModalPage1.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/M3MaterialNavigationBarSample_ModalPage2.xaml, src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs
related to https://github.com/unoplatform/uno.chefs/issues/128
- Bugfix
For cases where the NavBar's MainCommand should still be visible even if the BackStack is empty (such as modal pages where the MainCommand should be visible in order to close the flyout), we should be able to define the MainCommand.Icon and have the button visible in the NavBar like below:
We should also now be able to properly display the proper text on the NavBar's MainCommand using its Content or Label property
`<MainCommand Label="Return" />` should give:
=> fix: Ensure NavBar properly displays MainCommand button in all scenarios

.github/workflows/azure-static-webapp.yml
Azure Static WebApps failing the pr checks with:
> Reason: This Static Web App already has the maximum number of staging environments (10). Please remove one and try again.
Failure to deploy doesn't fail the check.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
=> ci: continue-on-error with Azure Static WebApps

doc/controls/LoadingView.md, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.cs
GitHub Issue (If applicable): closes #552
- Feature
LoadingView will always show a flicker of the loading state if transition has occurred before rendered (eg loading task completes before app activation). 
Disabling animations will prevent the loading state from being shown
=> feat: Adding ability to disable animations

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/RuntimeTestRunner.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml, src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarAutoLayoutPage2.xaml, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/NavBarAutoLayoutPage2.xaml.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationAppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarHelper.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/Renderer.cs
NavigationBars wrapped in an AutoLayout on iOS can result in a missing Back button icon/label. 
We need to ensure that we are rendering the Page's NavigationBar with the proper instance of the previous ViewController's UINavigationItem
=> fix(NavigationBar): Ensure proper iOS back button behavior

doc/controls/LoadingView.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/LoadingViewSample.xaml, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.xaml, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.cs, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.xaml
GitHub Issue (If applicable): #552
- Feature
This PR was prematurely merged https://github.com/unoplatform/uno.toolkit.ui/pull/553 with DisableAnimations as the property name
UseTransitions is more consistent with the useTransitions parameter passed to the GoToState method
Also switched visual states of both LoadingView and ExtendedSplashScreen to use VisualTransition instead of visual state storyboard so that useTransition will skip the animation.
=> Rename DisableAnimations to UseTransitions

src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.NetStandard.cs
GitHub Issue (If applicable): #563
- Bugfix
Doesn't load from file system when unpackaged WinUI
manifest file loaded from file system as fall back from applicationdata
=> fix: Loading appxmanifest.xml and package.appxmanifest from file or embedded resource

doc/controls-styles.md
GitHub Issue (If applicable): closes #456
- Bugfix
fixed broken links in `doc\controls-styles.md` page
=> docs: fix broken link

src/Uno.Toolkit.RuntimeTests/Helpers/XamlHelper.cs
GitHub Issue (If applicable): closes #572
- Bugfix
XamlHelper fails to parse input with xmlns'd attribute, like: `<Border x:Name="asd" />`
^ no more.
=> fix(test): XamlHelper unable to process xmlns'd attribute

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CardContentControlSamplePage.xaml, src/Uno.Toolkit.RuntimeTests/Tests/CardContentControlTests.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v2/CardContentControl.xaml
closes https://github.com/unoplatform/Uno.Figma/issues/675
closes https://github.com/unoplatform/Uno.Figma/issues/1226
closes https://github.com/unoplatform/Uno.Figma/issues/1443
closes https://github.com/unoplatform/Uno.Figma/issues/1401
Aligning CardContentControl with Material Guidance
- Bugfix
=> fix: align CardContentControl with material guidance

src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.NetStandard.cs
GitHub Issue (If applicable): #550 
- Bugfix
Extended splash on wasm has weird resizing effect
Extended splash is correctly positioned on screen
=> fix: Correct positioning of image

src/library/Uno.Toolkit.Material/Styles/Controls/v2/Card.xaml
GitHub Issue (If applicable): [[Gallery]Card- when changing theme Cards are not getting properly refreshed.](https://github.com/unoplatform/uno/issues/12104)
=> fix: Fixes Material Card themed backgrounds

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
GitHub Issue: Fixes #588
- Bugfix
In very specific cases, having SpaceBetween set, one fixed dimension parent and fixed size children, calculated parent dimension was been generated smaller then expected.
Now, parent size is been calculated as expected.
=> fix: SpaceBetween causing wrong size

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
GitHub Issue (If applicable): closes unoplatform/uno#8228
- Bugfix
As reported in Gallery app, TabBarItem's text is truncated when there's not enough space
TabBarItem's text is wrapped across multiple lines when horizontal space is not enough
=> fix: Fixes text truncation in TabBarItem

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs
closes https://github.com/unoplatform/uno.toolkit.ui/issues/546
- Bugfix
When you press on the theme toggle button WinUI and Wasm, it doesnt change the theme. 
Every time you press on the toggle button, it changes the theme.
https://github.com/unoplatform/uno.toolkit.ui/issues/546
=> fix(Theme): Fixed the theme toggle button for windows and WASM

samples/Directory.Packages.props
update packages to consolidate packages version
=> chore: update packages

src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs
fixes #381 
- Bugfix
When a property would change at runtime, the logic to re-register to the nested property callback was incorrectly using the `sender` instead of the actual owner of the sub-properties
=> fix: Properly resubscribe to nested prop changes

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters.xaml, src/Uno.Toolkit.UI/Controls/Chips/Chip.xaml, src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml
closes #561 
closes #597 
GitHub Issue (If applicable): #561 #597 
- Bugfix
Current behavior:
Overridden behavior:
Overridden with:
<Page.Resources>
<x:Double x:Key="ChipCheckGlyphSize">38</x:Double>
<x:Double x:Key="ChipContentMinHeight">40</x:Double>
<x:Double x:Key="ChipElevation">14</x:Double>
<x:Double x:Key="ChipHeight">38</x:Double>
<x:Double x:Key="ChipIconSize">38</x:Double>
<x:Double x:Key="ChipSize">40</x:Double>
<CornerRadius x:Key="ChipCornerRadius">0</CornerRadius>
<Thickness x:Key="ChipBorderThickness">5</Thickness>
<Thickness x:Key="ChipContentMargin">16,4</Thickness>
<Thickness x:Key="ChipPadding">16,4</Thickness>
<SolidColorBrush x:Key="ChipBackground" Color="Red" /> …
=> refactor(chip): Add lightweight styling to Chip style and add Fluent theme for Chip and ChipGroup

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
closes #594
GitHub Issue (If applicable): #594
Current behaviour:
Overriden:
Overriden with:
<Page.Resources>
<SolidColorBrush x:Key="TopTabBarItemBackground" Color="Red" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundPointerOver" Color="Orange" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundFocused" Color="Yellow" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundPressed" Color="Green" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundDisabled" Color="Blue" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundSelected" Color="Indigo" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundSelectedPointerOver" Color="Pink" />
<SolidColorBrush x:Key="TopTabBarItemBackgroundSelectedPressed" Color="Red" />
<SolidColorBrush …
=> refactor(tabbar): Add lightweight styling to tab bar style

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.Navigation.cs, src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationAppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Extensions/AppBarButtonExtensions.cs
related https://github.com/unoplatform/nventive-private/issues/487
related https://github.com/unoplatform/uno/issues/8996
fixes https://github.com/unoplatform/uno.toolkit.ui/issues/586
Fix error when using non-supported appbarbutton iconelement
Setting the Foreground property of a BitmapIcon has no effect when being used within the native renderers for CommandBar on iOS/Android
Foreground on BitmapIcon is respected and takes precedence over the Foreground of the AppBarButton
=> fix: NavBar Icon fixes

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
GitHub Issue (If applicable): #624
- Bugfix
Some control had wrong layout 
=> fix: Right padding becomes negative under certain conditions

samples/Directory.Packages.props, src/Directory.Packages.props
GitHub Issue (If applicable): closes #636
- Bugfix
skia head shows blank screen
^no more.
=> fix(skia): whitescreen

doc/controls/AutoLayoutControl.md
- Did not reflet the change from control to panel 
- counter and primary lenght are no longer deprecated
=> chore(Autolayout): doc update

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.Navigation.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Shell.xaml.cs
GitHub Issue (If applicable): closes #654
- Bugfix
DebugPanel is now hidden by default in DEBUG build, and can be activated by the settings button in the nav-niew.
=> chore(sample): hide debug panel

doc/helpers/command-extensions.md, doc/toc.yml
GitHub Issue (If applicable): unoplatform/private/issues/338
- Bugfix
controls-styles.md contains a deadlink to helper/command-extensions.md
- renamed helper/control-extensions.md to helper/command-extensions.md to match its associated class
- updated remaining to helper/control-extensions.md to the new location
regression from #385, where the link was updated, but the file was not renamed (which should've been done)
=> doc: fix deadlink

src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml, src/library/Uno.Toolkit.Cupertino/Styles/Controls/SlidingSegmentedControl.xaml
GitHub Issue (If applicable): closes #524 
- Bugfix
- Cupertino TabBar selector now is visually correct (selects the correct index).
- Added CornerRadius of 8 for base TabBar.
- Refactored `CupertinoSlidingSegmentedStyle` to not use the old SelectionIndicator
=> fix: cupertino tabbar sliding

src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
GitHub Issue (If applicable): #660
- Feature
Collapsed children are still measure
Collapsed children are not measure
=> feat(autolayout): collapsed children don't count in the measure

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/NavigationBarSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage1.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage2.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage2.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
https://github.com/unoplatform/uno.toolkit.ui/issues/595
https://github.com/unoplatform/uno.toolkit.ui/issues/541
- Feature
You cannot change the color of the navbar with lightWeight styling
Added LightWeight resources for the NavBar and fixed a fluent bug where the foreground would not change when changing theme.
=> feat(NavigationBar): Add lightweight styling to Navigation bar

samples/Directory.Packages.props, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Gtk/Program.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Skia.Wpf.Host/MainWindow.xaml.cs, samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Skia.Gtk/Program.cs, src/Directory.Packages.props
The namespace of GtkHost and WpfHost was just changed a little while ago.
=> chore(deps): Update Uno version

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Converters/HexToColorConverter.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowCollection.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Properties.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs
Part of #638 
Comments to be resolved in this PR:
PropertyMetadata.DefaultValue - https://github.com/unoplatform/uno.toolkit.ui/pull/638#discussion_r1268347423
Color Conversion - https://github.com/unoplatform/uno.toolkit.ui/pull/638#discussion_r1269457550
ToKey Invariant Culture - https://github.com/unoplatform/uno.toolkit.ui/pull/638#discussion_r1269460860
=> chore: Addressing Shadows PR remaining comments

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs
On the `RegisterDisposableNestedPropertyChangedCallback` we allocate an array and a `SerialDisposable` even when they aren't used. Moving the allocation inside the `if` will make sure we just allocate then if needed.
> Not sure if will be a case where that `if` will be `false`, if don't feel free to close this PR.
- Improvements
=> Avoid unnecessary allocations on DependencyObjectExtensions.RegisterDisposableNestedPropertyChangedCallback

samples/Directory.Packages.props, src/Directory.Packages.props
This PR just bumps the `Uno.Material` and `Uno.Material.WinUI` version.
- Bugfix
=> Bump Uno.Material and Material.WinUI version

samples/Directory.Packages.props, src/Directory.Packages.props
This PR just bumps the `Uno.Material` and `Uno.Material.WinUI` version.
- Bugfix
=> [Legacy] Bump Uno.Material and Material.WinUI version

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs
I'm not using the template, because I added two small fixes on the code.
1. Change the `SKShadow` to be a `readonly record struct`, I believe we want it to be immutable, and `record struct` isn't immutable, we to add the `readonly` modifier;
2. Use `Array.Empty<T>` to avoid allocations.
=> Small improvements

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/Shadow.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowCollection.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Properties.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs
GitHub Issue (If applicable): closes: #707
- Bugfix
ShadowContainer currently strips its child's background and use it as the background for the image-brush. This is done because the inner shadows need to be drawn on top of the content background. This approach has a few problems where it doesnt subscribes to updates to the background property, nor theme updates from the `{ThemeResource}` brush.
ShadowContainer now creates two layers of shadows, one for background shadows and one for foreground shadows, that sandwiches the content.
=> fix(shadows): background theming issue

src/library/Uno.Toolkit.Material/Styles/Controls/v2/CardContentControl.xaml
closes #706
GitHub Issue (If applicable): #706 
- Bugfix
Adding Elevated CardContentControls to an ItemsRepeater that defines its own Spacing between items causes more spacing between the cards than intended because of the [margin applied to the ElevatedView](https://github.com/unoplatform/uno.toolkit.ui/blob/1ce1eb5bcb34d2ca42b23cdf4f5515d1ec9ccb09/src/library/Uno.Toolkit.Material/Styles/Controls/v2/CardContentControl.xaml#L235)
The [margin applied to the ElevatedView](https://github.com/unoplatform/uno.toolkit.ui/blob/1ce1eb5bcb34d2ca42b23cdf4f5515d1ec9ccb09/src/library/Uno.Toolkit.Material/Styles/Controls/v2/CardContentControl.xaml#L235) is now templatebound to Margin so we can set …
=> fix: Templatebound Margin to remove hardcoded margin

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.UWP/Uno.Toolkit.Samples.UWP.csproj
Improves build speed by removing UWP .NET native build
=> ci(perf): Disable unused .NET native for uwp

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ShadowContainerSamplePage.WinUI.xaml, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs, src/Uno.Toolkit.Skia.WinUI/Themes/Generic.xaml, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer.cs
GitHub Issue (If applicable): closes #708
- Feature
ShadowContainer content not stretching by default
ShadowContainer content should stretch by default to allow controls inside to properly stretch also if needed
NeumorphismHollow
NeumorphismRaising
=> [WinUI/ShadowContainer] ShadowContainer content not stretching by default #708

doc/controls-styles.md, doc/controls/Divider.md, doc/lightweight-styling.md, doc/toc.yml, samples/Directory.Packages.props, src/Directory.Packages.props, src/library/Uno.Toolkit.Material/Styles/Controls/v2/Divider.xaml
- Feature
There's not lightweight styling and the foreground of the divider is not following the latest figma file.
Correct the foreground color and added lightweight styling and documentation
=> feat: add lightweight styling to divider

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs
GitHub Issue (If applicable): #748
- Bugfix
Right now, on skia, and IOS you add a shadow to a shadow container and increase the size of the shadow content, the shadows appear too small, 
They stay the right size and visible
=> fix: skia and IOS shadows not updating properly

src/Uno.Toolkit.RuntimeTests/Tests/ShadowContainerTests.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs
fixes https://github.com/unoplatform/uno.toolkit.ui/issues/803
=> fix(ShadowContainer): ensure canvas does not have negative dimension

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ShadowContainerSamplePage.WinUI.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ShadowContainerSamplePage.WinUI.xaml.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs
GitHub Issue (If applicable): closes: #798 
- Bugfix
ShadowContainer is correctly stretching iwhen the content is changed to be larger but if the content is then shrunk, the ShadowContainer does not resize:
See Shadow Builder control inside of the Toolkit sample app:
Removed some commented code and conditional layout refactoring.
Now the Canvas free up allocated space so content can reduce in size.
https://github.com/unoplatform/uno.toolkit.ui/assets/116665025/723a897e-40e8-43f3-b82d-ceb3cdbb99ec
=> [ShadowContainer][All Platforms] ShadowContainer not resizing properly

doc/controls/ShadowContainer.md
GitHub Issue (If applicable): closes #814
Updated docs with breaking changes from #752.
n/a
=> docs(shadows): add remarks about shadow background

doc/toc.yml
- Bugfix
add missing ShadowContainer entry to Table of Contents
=> doc(toc): add missing shadows entry

doc/material-migration.md
related https://github.com/unoplatform/Uno.Themes/issues/1170
=> docs: add migration for lightweight styling

build/workflow/stage-uitests-ios.yml, src/Uno.Toolkit.RuntimeTests/Tests/ShadowContainerTests.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs
GitHub Issue (If applicable): closes: #789 
For better performance.
Using array.
=> [ShadowContainer] CornerRadius performance issue

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer.cs
GitHub Issue (If applicable): closes #782
- Bugfix
We do not have cache control for CornerRadius.
Now we have the cache control for corner radius.
=> [ShadowContainer] Cache issue on CornerRadius 

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
GitHub Issue (If applicable): #851
- Bugfix
fill children was given the appropriate size information 
fill children are properly count and assigned size 
=> fix(AutoLayout): check for filledChildrenCount was inverse

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ShadowContainerSamplePage.WinUI.xaml, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowsCache.cs
Multiple shadows repaint were made because of comparison of records through an interface.
The base interface was replaced by an abstract record.
Another repaint was also sometimes made due to the fact that we didn't take into account the uninitialized pixel ratio.
=> fix(ShadowContainer): prevent unnecessary repaint

src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowsCache.cs
Implement shadows cache cleanup based on stats.
Removed debug.writeline.
Duplicate of https://github.com/unoplatform/uno.toolkit.ui/pull/698 but with correct PR source.
All reviews comments were resolved.
@pictos @Xiaoy312
=> feat(ShadowContainer): cache cleanup based on shadows stats

src/Uno.Toolkit.UI/Behaviors/StatusBar.cs
GitHub Issue (If applicable): closes #866, closes unoplatform/uno.chefs#666
- Bugfix
On pages using StatusBar, apps using Toolkit.UI crash when changing the Windows OS theme in the OS Settings:
"The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))"
No crash
=> fix(StatusBar): OS theme change no longer crashes app

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
fixes https://github.com/unoplatform/uno.toolkit.ui/issues/874
- Bugfix
=> fix: templatebind background to ios navbar template

src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/Renderer.cs
closes #885 
- Bugfix
A crash when navigating from and then back to a page with a NavigationBar on it
No crash
=> fix: avoid creating disconnected native navbars on load

src/library/Uno.Toolkit.WinUI.Markup/Uno.Toolkit.WinUI.Markup.csproj, src/library/Uno.Toolkit.WinUI.Material.Markup/Uno.Toolkit.WinUI.Material.Markup.csproj
- addresses build failure in unoplatform/uno.templates#371
- Bugfix
Markup packages are missing windows10 target
Markup packages match the same targets as Uno.Toolkit.WinUI
=> Adding missing winui targets for markup packages

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs
- Bugfix
```
<utu:AutoLayout PrimaryAxisAlignment="Center" Width="300" Height="300" Background="Pink">
<TextBlock Text="Oh no!" utu:AutoLayout.CounterAlignment="Center" />
<Button Content="Something went wrong" utu:AutoLayout.CounterAlignment="End"/>
</utu:AutoLayout>
```
producing
- [] Associated with an issue (GitHub or internal)
=> fix(autoLayout): when hug and have a alignment

src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs
=> fix: Ensure bindings are set once presenter has owner set

samples/Directory.Packages.props, src/Directory.Packages.props, src/Uno.Toolkit.RuntimeTests/Tests/ItemsRepeaterExtensionTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/NavigationBarTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
fixes from canary failures
update winappsdk
fix padding improperly set on tabbar
fix failing tests
=> fix: fix tests and build failures and incorrect padding

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
GitHub Issue (If applicable): #923
- Bugfix
- Centered child are strickly center independ of the padding 
- use relative center with padding
=> fix: make center with padding behave like figma

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs
GitHub Issue (If applicable): closes #927
- Bugfix
On android, DrawerFlyout can open with 0-length in certain situation.
^ no more
internal drawer constraint calculation was done too early, before ActualSize was set.
=> fix(drawerflyout): empty flyout in certain situation

Directory.Build.targets, samples/Directory.Packages.props, src/Directory.Packages.props
GitHub Issue (If applicable): re: #736, closes #929
just rehosting pr, due to ci currently not able to sign from foreign repo
=> build: Use compiler from SDK instead of NuGet package to reduce developer friction

doc/controls/Divider.md
add copy-pastable usage examples for Divider control
=> docs: adjust Divider usage examples

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
GitHub Issue (If applicable): #919
- Bugfix
a hug autolayout with counter alignement set to center inside a autolayout was not properly centered
centered
=> fix: hug center now properly centered

doc/helpers/responsive-extension.md, doc/toc.yml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/ResponsiveExtensionsSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/ResponsiveExtensionsSamplePage.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveExtensionsTests.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs, src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs
GitHub Issue (If applicable):
closes https://github.com/unoplatform/uno.chefs/issues/723
Currently, there is no clean and concise way to handle responsive layouting with XAML. The main way of accomplishing this is through [Visual States and AdaptiveTriggers](https://learn.microsoft.com/en-us/windows/apps/design/layout/layouts-with-xaml#set-visual-states-in-xaml-markup).
This PR introduces a custom markup extension called `ResponsiveExtension` that allows for any property to be dynamically set.
=> feat: Responsive markup extension

doc/controls/ResponsiveView.md, doc/helpers/responsive-extension.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/ResponsiveViewSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/ResponsiveExtensionsSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.Properties.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.cs, src/Uno.Toolkit.UI/Extensions/EnumerableExtensions.cs, src/Uno.Toolkit.UI/Helpers/ResourceHelper.cs, src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs
GitHub Issue (If applicable): closes #945, closes #941
- Feature
=> responsive enhancements

src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.Properties.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.cs, src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs
GitHub Issue (If applicable): closes #951
ResponsiveExpression performs value conversion and binding update on at every size changed proc.
- ^ it will only do so when significant layout change (eg: going from Normal->Wide) has occurred since last update.
- improved TreeGraph output details for ResponsiveView & ResponsiveExpression
- refactored ResponsiveView's & ResponsiveExpression's shared logics into ResponsiveHelper
=> perf(ResExpr): prevent unnecessary updates

src/Uno.Toolkit.UI/Controls/TabBar/TabBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
closes https://github.com/unoplatform/uno.toolkit.ui-private/issues/8
- Bugfix
=> fix: avoid clipping fabtabbaritem

doc/controls/ResponsiveView.md, doc/helpers/responsive-extension.md, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveHelperTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveViewTests.cs, src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs
GitHub Issue (If applicable): closes #965
- Bugfix
given only {normal, wide, widest} are provided:
=> fix(responsive): layout breakpoint calculation

doc/controls/ResponsiveView.md, doc/helpers/responsive-extension.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.cs, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveExtensionsTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveHelperTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveViewTests.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.cs, src/Uno.Toolkit.UI/Helpers/ResponsiveHelper.cs, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.not-supported.cs
GitHub Issue (If applicable): closes #942
removed the needs of ResponsiveHelper.HookEvent, and adjusted the docs around that part.
=> refactor(responsive): remove ResponsiveHelper initialization

src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs
GitHub Issue (If applicable): closes #998
- Bugfix
ResponsiveExtension (binding) is returning the initial default value created by Activator.CreateInstance when the size is not available. This can cause a problem where the default value of said type is not a valid value, such as a the case for Grid.RowSpan.
User defined enums cannot be parsed.
The initial default value returned will now be the first member defined within: Narrowest...Widest. The reasoning being that, if it is defined it has to be more valid than just the `default(T)`.
User defined enums can now be parsed by ResponsiveExtension correctly.
=> fix(responsive): invalid initial value being returned

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
- Bugfix
- when counterAlignment set to stretch end padding is not always applied
- when counterAlignment set to stretch end padding is always applied
=> fix: autolayout counterAlignment stretch had a wrong padding

doc/controls/DrawerControl.md, doc/controls/DrawerFlyoutPresenter.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerControlSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/DrawerFlyoutSamplePage.xaml, src/Uno.Toolkit.UI/Behaviors/DrawerControlBehavior.cs, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.Enhanced.xaml, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.Properties.cs, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.Properties.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.cs, src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.xaml
GitHub Issue (If applicable): closes #1005
- Feature
added IsLightDismissEnabled property for both DrawerControl and DrawerFlyoutPresenter that can be used to prevent light-dismiss.
=> feat(drawer): IsLightDismissEnabled

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.xaml
- Bugfix
drawerflyout are now throwing: Property 'MaxWidth' cannot be set to NaN. It must not be NaN or negative.
not throwing anymore
the error were introduced by: https://github.com/unoplatform/uno/pull/15050
but it is not supposed to throw (as evidenced by windows)
although, microsoft does suggested that: "This value can be any value equal to or greater than 0. PositiveInfinity is also valid."
on windows, setter with value of `NaN` or `PositiveInfinity` both results in +inf.
\---
note that the setters are needed to override the (758x456) values from the default style
=> chore: fix maxwidth=nan throw

build/workflow/stage-build-android.yml, build/workflow/stage-build-ios.yml, build/workflow/stage-build-packages.yml, build/workflow/stage-validations.yml, build/workflow/templates/gitversion.yml
=> ci: Cleanup

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs
Fixes https://github.com/unoplatform/uno.toolkit.ui/issues/1022
As described in the issue, a stretched child of an AutoLayout were not properly arranged when inside a ScrollViewer.
When the `finalSize` is different than the one used to measure the element (which is the case in a ScrollViewer), it was incorrectly using the measured size instread of recalculating it using the `finalSize`.
=> AutoLayout wasn't arranging stretched children when in ScrollViewer

doc/controls/ChipAndChipGroup.md, src/Uno.Toolkit.UI/Controls/Chips/Chip.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml, src/library/Uno.Toolkit.WinUI.Markup/Theme/Chip.cs
closes https://github.com/unoplatform/uno.toolkit.ui/issues/993
- Bugfix
- Feature
=> fix(chip): remove check-glyph

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/LoadingViewSample.xaml, src/Uno.Toolkit.UI/Behaviors/ProgressExtensions.cs, src/Uno.Toolkit.UI/Behaviors/ProgressRingExtensions.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.xaml, src/Uno.Toolkit.UI/Controls/LoadingView/LoadingView.xaml
Fixes: https://github.com/unoplatform/uno.chefs/issues/835
- Bugfix
- Feature
ProgressRing contained within the loading template doesn't ever stop (ie IsActive is true)
New ProgressRingExtensions.IsActive can be used to start/stop all nested ProgressRings
In VisualState for Loading/Loaded any ProgressRings can have IsActive set to true/false
=> feat: Adding ProgressRing extension

src/library/Uno.Toolkit.Cupertino/Styles/Controls/SlidingSegmentedControl.xaml
GitHub Issue (If applicable):  #1021 
- Bugfix
Using TabBar control with CupertinoSlidingSegmentedStyle renders ui with fixed height
Using TabBar control with CupertinoSlidingSegmentedStyle renders ui with adaptable height
=> fix(CupertinoSlidingSegmentedStyle): change height to minheight

doc/controls-styles.md, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/_Common.xaml, src/library/Uno.Toolkit.WinUI.Markup/Theme/TabBarItem.cs
related https://github.com/unoplatform/Uno.Figma/issues/2312
related: https://github.com/unoplatform/Uno.Figma/pull/2316
=> chore: expose base navigation and fab tabbaritem styles

src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
closes #1039
- Bugfix
with content only tabBar item, if the text is too long, it is cutted off.
support larger text with may tabs created.
https://github.com/unoplatform/uno.chefs/issues/937
=> fix: cutted text with content only long text

doc/helpers/progress-extensions.md, doc/toc.yml
GitHub Issue (If applicable): #1038 
Not documented.
...documented!?
Internal Issue (If applicable): N/A
=> docs: Add page for ProgressExtensions

doc/controls/NavigationBar.md, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UITest/Controls/NavigationBar/Given_NavigationBar.cs
closes #1041
closes #623
closes https://github.com/unoplatform/uno.toolkit.ui/issues/455
=> fix: enable any iconelement for navigationbar on mobile

build/workflow/cspell.json, doc/helpers/StatusBar-extensions.md, src/Uno.Toolkit.UI/Behaviors/DrawerControlBehavior.cs
GitHub Issue (If applicable): closes #1055
- Bugfix
using certain DrawerControlBehavior attached properties on a NavigationView would result in a compilation error:
- DrawerBackground
- FitToDrawerContent
^ should not happen
=> fix(drawer): attached property crash

samples/Uno.Toolkit.WinUI.Samples/Uno.Toolkit.WinUI.Samples.Windows.Desktop/Uno.Toolkit.WinUI.Samples.Windows.Desktop.csproj, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Android.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.NetStandard.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.iOS.cs
We currently allow users of `ExtendedSplashScreen` to get/set a `SplashScreen` object ([`Windows.ApplicationModel.Activation`](https://learn.microsoft.com/uwp/api/windows.applicationmodel.activation)) which appears to not be implemented for Uno.UI targets.
Remove [`ExtendedSplashScreen.SplashScreen`](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/ExtendedSplashScreen.html#properties) property
=> chore: Remove property for UAP splash entity

doc/controls/ChipAndChipGroup.md, doc/controls/TabBarAndTabBarItem.md, doc/material-migration.md, src/library/Uno.Toolkit.Material/Styles/Controls/v2/Chip.xaml, src/library/Uno.Toolkit.Material/Styles/Controls/v2/TabBar.xaml
closes https://github.com/unoplatform/uno.toolkit.ui/issues/1086
Adjust brush usages now that https://github.com/unoplatform/Uno.Themes/pull/1369 has merged into Themes. Change usages of `-DisabledLowBrush` to `-DisableBrush`
=> fix: adjust opacity brushes from themes breaking change

doc/helpers/responsive-extension.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Helpers/ResponsiveExtensionsSamplePage.xaml, src/Uno.Toolkit.UI/Behaviors/ResponsiveBehavior.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.cs, src/Uno.Toolkit.UI/Markup/ResponsiveExtension.not-supported.cs
GitHub Issue (If applicable): closes #950
- Bugfix
- Feature
previously ResponsiveExpression didnt support non-FrameworkElement targets such as Grid.ColumnDefinitions or TextBlock.Inlines.
^ they are now supported.
=> feat(responsive): add support for non-FrameworkElement

src/Uno.Toolkit.UI/Behaviors/ProgressExtensions.cs
GitHub Issue (If applicable): #1099
- Bugfix
Progressring in loadingcontenttemplate not being stopped - the search was stopping at the contenttemplate, rather than interrogating all children
Progressring is being stopped
=> fix: Ensure all progressrings stop

doc/controls/ExtendedSplashScreen.md
GitHub Issue (If applicable): #574 
=> docs: Update ExtendedSplashScreen documentation

src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs
Fix for case when you are using an ItemsSource that is not a source of TabBarItem directly. 
Setting the SelectedItem would not work previously
=> fix: selecteditem logic when itemssource is not tabbaritem

doc/helpers/Input-extensions.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/InputExtensionsSamplePage.xaml, src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs
GitHub Issue (If applicable): closes #1119 
- Feature
- Small sample 
- Documentation addition
We have to specify `android:ImeOptions="Next"` and `ios:ReturnKeyType="Next"` if we want the return key on soft-keyboards to be Next.
We only have to add `utu:InputExtensions.ReturnType="Next"` and Toolkit will handle the device specific cases itself.
=> feat: added inputextensions returntype property

src/Uno.Toolkit.RuntimeTests/Tests/AutoLayoutTest.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Arrange.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Layouting.Measure.cs, src/Uno.Toolkit.UI/Controls/AutoLayout/AutoLayout.Properties.cs
Fixes https://github.com/unoplatform/uno.toolkit.ui/issues/1131
In some situations, it was possible to crash the UI in WinUI, launching an invalidation loop.
Now works properly on both WinUI and Uno. Child elements are not remeasured during arrange phase, we're just using their desired size to layout them.
=> Prevent AutoLayout from causing an invalidation loop on WinUI

doc/helpers/command-extensions.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml.cs, src/Uno.Toolkit.UI/Behaviors/CommandExtensions.cs
GitHub Issue (If applicable): #1140
- Feature
CommandExtensions.Command only supports a limited set of controls
It is now supported on any UIElement.
=> feat: CommandExtensions.Command on any control

build/workflow/stage-determine-changes.yml, doc/controls/DrawerFlyoutPresenter.md, doc/controls/ExtendedSplashScreen.md, doc/controls/LoadingView.md, doc/controls/NavigationBar.md, doc/controls/ResponsiveView.md, doc/controls/SafeArea.md, doc/controls/ShadowContainer.md, doc/getting-started.md, doc/helpers/StatusBar-extensions.md, doc/helpers/resource-extensions.md, doc/lightweight-styling.md, doc/toc.yml
- Build or CI-related changes
- Include .markdownlint.json and cspell.json as part of the documentation
- Removing `<iframe />` for the youtube videos and use proper markdown `[!video link]` instead
- Fix a couple of additional markdown display issues
(Following changes for Uno core repo: https://github.com/unoplatform/uno/pull/16972)
=> docs: Documentation adjustments

src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.crossruntime.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.xaml, src/Uno.Toolkit.UI/Extensions/EnumerableExtensions.cs
GitHub Issue (If applicable): closes unoplatform/uno#16725
- Bugfix
Opacity applied from fade out animation caused multiple colors layers to be displayed in splash screen.
Workarounded by disabling the animation.
Background existing in both resizetizer generated splashscreen image and in the wrapping grid.
=> fix(splash): apply workaround for layered background bug

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs
GitHub Issue (If applicable): #1150 
- Bugfix
=> fix: ArgumentOutOfRangeException when adding PrimaryCommand to NavBar

src/Uno.Toolkit.RuntimeTests/Tests/DrawerTests.cs, src/Uno.Toolkit.UI/Controls/DrawerControl/DrawerControl.cs, src/Uno.Toolkit.UI/Helpers/DispatcherCompat.cs
GitHub Issue (If applicable): closes unoplatform/uno.toolkit.ui#1162
- Bugfix
fixed a couple exceptions related to DrawerControl.IsOpen
=> fix(drawer): DrawerControl.IsOpen exceptions

src/Uno.Toolkit.UI/Behaviors/CommandExtensions.cs
- Bugfix
non-sense warning being logged erroneously:
> Uno.Toolkit.UI.CommandExtensions: Warning: CommandExtensions.Command is not supported on 'Microsoft.UI.Xaml.Controls.PasswordBox'.
^ no more.
=> fix: CommandExtensions warning on Text/PasswordBox

doc/helpers/command-extensions.md, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/Controls/CommandExtensionsSamplePage.xaml.cs, src/Uno.Toolkit.UI/Behaviors/CommandExtensions.cs
- Bugfix
- CommandExtensions.Command is not supported on Selector (except ListView)
- CommandExtensions.CommandParameter resolution for NavigationView and Selector doesnt work on their item-container or item-template's root
- Command now works on Selector
- CommandParameter now correctly resolves from item-container or item-template's root of NavigationView and Selector (barring ListView)
=> fix(CommandExtensions): parameter resolution & add support for Selector

src/Uno.Toolkit.UI/Behaviors/ResourceExtensions.cs, src/Uno.Toolkit.UI/Extensions/ResourceDictionaryExtensions.cs
GitHub Issue (If applicable): closes #1187
- Bugfix
ResourceExtensions.Resource no longer throw ArgumentException on windows when re-using the same resource-dictionary, such as when used in style setter.
=> fix: ResourceExtensions throwing ArgumentException on windows

src/Uno.Toolkit.RuntimeTests/Tests/ExtendedSplashScreenTests.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Android.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.crossruntime.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.iOS.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.macOS.cs
GitHub Issue (If applicable): closes #1185
- Bugfix
wasm splashscreenn should no longer throw
regression from: #1151
=> fix: wasm splashscreen exception

src/Uno.Toolkit.RuntimeTests/Tests/DependencyObjectExtensionTests.cs, src/Uno.Toolkit.UI/Extensions/DependencyObjectExtensions.cs
GitHub Issue (If applicable): closes #1198
- Bugfix
FindDependencyProperty on an overridden property throws:
> System.Reflection.AmbiguousMatchException: 'Ambiguous match found for 'Microsoft.UI.Xaml.UIElement Microsoft.UI.Xaml.Visibility Visibility'.'
^ No more.
=> fix: FindDependencyProperty AmbiguousMatchException

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/TestPages/ShadowContainerTestPage2.WinUI.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/TestPages/ShadowContainerTestPage2.WinUI.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.Paint.cs, src/Uno.Toolkit.Skia.WinUI/Controls/Shadows/ShadowContainer.cs, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer2.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17366
=> fix: ShadowContainer on wasm wasn't repainting when unloaded then loaded

build/workflow/stage-uitests-android.yml, build/workflow/stage-uitests-ios.yml, build/workflow/stage-uitests-wasm.yml
We should be failing the task of publishing the test results if the results file doesn't exist
This will allow us to catch things like [this](https://github.com/unoplatform/Uno.Gallery/issues/1154) earlier
=> ci: fail test publish task if file is missing

src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.crossruntime.cs
GitHub Issue (If applicable): #1165
- Bugfix
The url being returned is `file:\C:\C\1165\UnoApp1\UnoApp1\bin\Debug\net8.0-windows10.0.19041\AppxManifest.xml`. When `File.Exist` uses that url, it returns false due to the "file" prefix.
No "file" prefix.
=> fix: Get the correct file path

src/Uno.Toolkit.RuntimeTests/Tests/AncestorBindingTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/AncestorBindingTest.xaml, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/AncestorBindingTest.xaml.cs, src/Uno.Toolkit.UI/Markup/AncestorBindingExtension.cs
GitHub Issue (If applicable): closes #1218, closes #1219
- Bugfix
AncestorBinding when used on non-reference type dp would cause a COMException. This is due to it returning `null` as initial default value, until the binding came online.
The current value will now be returned, prevent this COMException.
=> fix: ancestor-binding initial value type incompatibility

src/Uno.Toolkit.RuntimeTests/Tests/ItemsRepeaterExtensionTests.ISelectionInfo.cs, src/Uno.Toolkit.UI/Behaviors/ItemsRepeaterExtensions.cs, src/Uno.Toolkit.UI/Controls/ExtendedSplashScreen/ExtendedSplashScreen.Windows.crossruntime.cs, src/Uno.Toolkit.UI/Helpers/RuntimeInfoHelper.cs
GitHub Issue (If applicable): closes #1194 
- Bugfix
When setting ItemsRepeater with multiselection and preselected items, they are not part of SelectedItems after creation, so they only appear visually selected but not in the code behind.
There was a delay between setting the ItemsSource and ItemsSourceView, now we set SelectedItems after the ItemsSourceView.CollectionChanged event is triggered.
=> fix: wasm itemsrepeater multiselection

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/TestPages/ShadowContainerTestPage2.WinUI.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/TestPages/ShadowContainerTestPage2.WinUI.xaml.cs, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer2.cs
fixes flaky test occasionally breaking canary builds
=> fix: flaky test

src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer2.cs
When_Unloaded_Then_Loaded runs, the test sometimes fails because the pixel color diff between the two screenshots comparison is slightly more than the default tolerance of 5
=> fix: increase pixel diff tolerance for flaky test

.github/workflows/azure-static-webapp.yml, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer2.cs
Even though the pixel tolerance is set to 10, we still fail if the required difference is exactly 10:
> initial:
> 396,0: expected: [717,84] FFFCFBFF | actual: [717,84] FFF9F7FC
> 	a tolerance of 10 [Cumulative] would be required for this test to pass.
> 	Current: Color Cumulative tolerance of 10 | Location PerRange tolerance of 0,0 pixels.
Increase it to avoid this
=> chore: increase test pixel tolerance

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/TestPages/ShadowContainerTestPage2.WinUI.xaml, src/Uno.Toolkit.UITest/Controls/ShadowContainer/Given_ShadowContainer2.cs
Use a fully opaque shadow to compare screenshots with
Before:
After:
=> chore: fix flaky shadow test

src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeFramePresenter.iOS.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18401
- Bugfix
`OnTemplatedParentChanged` no longer triggers
Use `Loaded` event instead
=> fix: Adjust `NativeFramePresenter` to work with new `TemplatedParent`

src/Uno.Toolkit.RuntimeTests/Tests/AncestorBindingTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/DrawerTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/ExtendedSplashScreenTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveExtensionsTests.cs
=> fix: UWP Build

doc/helpers/ancestor-itemscontrol-binding.md, src/Uno.Toolkit.RuntimeTests/Tests/AncestorBindingTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/AncestorBindingTest.xaml, src/Uno.Toolkit.RuntimeTests/Tests/TestPages/AncestorBindingTest.xaml.cs, src/Uno.Toolkit.UI/Helpers/VisualTreeHelperEx.cs, src/Uno.Toolkit.UI/Markup/AncestorBindingExtension.cs
GitHub Issue (If applicable): closes #1283
- Feature
no Converter support for AncestorBinding
AncestorBinding now supports Converter, ConverterParameter, ConverterLanguage.
=> feat: add Converter support for AncestorBinding

src/Uno.Toolkit.RuntimeTests/Tests/ChipGroupTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/TabBarTests.cs, src/Uno.Toolkit.UI/Extensions/ItemsControlExtensions.cs
GitHub Issue (If applicable): closes #1281
- Bugfix
xaml-defined TabBar and ChipGroup initial selection is being discarded.
^ should no longer happen.
shadowing #1286
=> fix: workaround for tabbar&chip initial selection being discarded

src/Uno.Toolkit.Skia.WinUI/Themes/Generic.xaml
GitHub Issue (If applicable): closes #1139, closes #1184
- Bugfix
On skia and wasm, the hitbox of ShadowContainer is much larger than its visual/content (depending on the shadows used), often prevent neighboring elements from receiving pointer events.
The shadow layer is now `IsHitTestVisible=False`, and no longer interferes with _clickability_ of neighboring elements.
from observation, this issue seems to only impact skia and wasm. windows, android and ios are unaffected.
=> fix: skia+wasm shadow-container hitbox

src/Uno.Toolkit.UI/Controls/Chips/ChipGroup.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBar.cs, src/Uno.Toolkit.UI/Controls/TabBar/TabBarListPanel.cs, src/Uno.Toolkit.UI/Extensions/ItemsControlExtensions.cs
GitHub Issue (If applicable): closes #1287, closes #1293
- Bugfix
Various dp handler and initialization method for chips and tabbar are affected by the unavailability of ItemsPanelRoot at during Loaded time.
These methods are called again when ItemsPanelRoot becomes available.
=> workaround for regressions caused by ItemsPanelRoot resolution timing

src/Uno.Toolkit.UI/Controls/ZoomContentControl/ZoomContentControl.xaml
GitHub Issue (If applicable): #1291 
- Bugfix
Fixes ZoomContentControl on WinAppSdk
Additional information can be found here: https://github.com/unoplatform/uno.toolkit.ui/issues/1291#issuecomment-2506770279
=> fix: ZoomContentControl WinAppSdk

samples/Directory.Packages.props, src/Uno.Toolkit.RuntimeTests/Tests/ChipGroupTests.cs, src/Uno.Toolkit.RuntimeTests/Tests/DrawerFlyoutTests.cs
bump samples to latest stable 5.5.x Uno
Adjust tests now failing with latest Uno due to TemplatedParent changes
=> chore: uno samples bump + adjust tests

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage2.xaml, src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs, src/Uno.Toolkit.UITest/Controls/NavigationBar/Given_NavigationBar.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18506
- Bugfix
In Fluent theme, clicking on an `AppBarButton` inside a `NavigationBar` with any kind of `Icon` set makes it unresponsive. The Click event never fires because the `AppBarButton`'s `Icon` is rendered at every click, since the Color is changing opacity.
`AppBarButton` click works in both Fluent and Material theme.
=> fix: AppBarButton inside NavigationBar keeps rendering on every click

doc/controls-styles.md, doc/helpers/SystemThemeHelper.md, doc/toc.yml
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/pull/19235, https://github.com/unoplatform/uno.toolkit.ui/pull/1324
=> docs: Add `SystemThemeHelper` page

src/Uno.Toolkit.UI/Helpers/SystemThemeHelper.cs
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/pull/19235
- Bugfix
=> chore: Mark SystemThemeHelper methods as obsolete

samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/App.xaml.Navigation.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage1.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage1.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage2.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage3.xaml, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Content/NestedSamples/FluentNavigationBarSampleNestedPage3.xaml.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Controls/SamplePageLayout.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.Shared/Uno.Toolkit.Samples.Shared.projitems, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.Android.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs, src/Uno.Toolkit.UITest/Controls/NavigationBar/Given_NavigationBar.cs, src/Uno.Toolkit.UITest/Controls/NavigationBar/Given_NavigationBar_Fluent.cs, src/Uno.Toolkit.UITest/TestBase.cs
GitHub Issue (If applicable): closes #1334 
- Bugfix
iOS NavigationBar lifecycle wasn't handled correctly since on iOS the NavBar is always UnLoaded by default when navigating away. 
Added OnLoaded for both iOS and Android `NavigationBarPresenter`
=> fix: ios navbar lifecycle

src/Uno.Toolkit.UI/Controls/NavigationBar/NativeNavigationBarPresenter.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarNavigationItemRenderer.iOS.cs, src/Uno.Toolkit.UI/Controls/NavigationBar/Renderer.cs
fixes https://github.com/unoplatform/private/issues/617
fixes https://github.com/unoplatform/private/issues/645
Handles Hot Reload scenario where the content of a Page is copied over to a new Page instance and is then set as the Content on the original Page instance.
To avoid an invalid re-render of the UINavigationBar, clear the renderer registrations of the original NavigationBar when unloaded. The NativeFrameHelper will automatically re-wire the renderers when the wrapping UIViewController is about to appear.
=> fix: hot reload ios support for navigationbar

src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
fixes https://github.com/unoplatform/uno.chefs/issues/1489
Previous change for AppBar height did not get changed for both theme dictionaries
=> chore: adjust navbar themeresources to match between themes

version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/7.0, based on #1375
=> Version bump after 7.0 release branch

src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs, src/library/Uno.Toolkit.Material/Styles/Controls/v2/NavigationBar.xaml
related https://github.com/unoplatform/uno-private/issues/1163
Do not override Fluent CommandBar-related resources globally, set the Height explicitly on the CommandBar
=> fix: navigationbar commandbar staticresources

global.json, samples/Directory.Packages.props, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples/Platforms/Desktop/Program.cs, samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples/Uno.Toolkit.Samples.csproj
Fix errors for toolkit sample app on main
=>  chore: bump uno samples app version to 6

src/Uno.Toolkit.UI/Controls/DrawerFlyout/DrawerFlyoutPresenter.xaml
GitHub Issue (If applicable): close unoplatform/uno-private#1265
- Bugfix
Strange 1px border appears on DrawerFlyout
^ no more
=> fix: remove 1px border on drawer-flyout

src/Uno.Toolkit.RuntimeTests/Tests/InputExtensionsTests.cs, src/Uno.Toolkit.UI/Behaviors/InputExtensions.cs
GitHub Issue (If applicable): closes #1418
- Bugfix
- Passing `XamlRoot.Content` as SearchRoot so that InputExtensions.AutoFocusNext="True" no longer throws on Android(`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Focus navigation directions Next, Previous, and None are not supported when using FindNextElementOptions')`)
=> fix: AutoFocusNext crash on android

version.json
Bump version to 8.0 for breaking change introduced by https://github.com/unoplatform/uno.toolkit.ui/pull/1417
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/8.0, based on #1423
=> Version bump after 8.0 release branch

version.json
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/8.1, based on #1432
=> Version bump after 8.1 release branch

src/Uno.Toolkit.RuntimeTests/Tests/ResponsiveViewTests.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.cs, src/Uno.Toolkit.UI/Controls/ResponsiveView/ResponsiveView.xaml
GitHub Issue (If applicable): closes #1442
ResponsiveView exposes the Content property which also marked by the [ContentProperty]. This confuses the HotDesign as it treats dynamic content (resolved templated is materialized into Content) as RV's logical child, and incorrectly adds it as RV's Content.
Resolved template is now materialized under a border that is within the ControlTemplate, so it won't be picked up by HotDesign.
=> refactor: resp-view

version.json
GitHub Issue (If applicable): closes unoplatform/dispatchscience-private#26
- Bugfix
- added workaround for drawer flyout with ItemsRepeater not materializing its items
- fixed drawer flyout would re-open without animation when it was previously dismissed from focus lost
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/8.2, based on #1449
=> Version bump after 8.2 release branch

src/crosstargeting_override.props.sample
Adjust hint for crosstargeting override file after move to net9
=> chore: Adjust hint for crosstargeting override after move to net9
